//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"mime/multipart"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for BulkDecisionItemAction.
const (
	BulkDecisionItemActionConfirmed BulkDecisionItemAction = "confirmed"
	BulkDecisionItemActionDismissed BulkDecisionItemAction = "dismissed"
)

// Valid indicates whether the value is a known member of the BulkDecisionItemAction enum.
func (e BulkDecisionItemAction) Valid() bool {
	switch e {
	case BulkDecisionItemActionConfirmed:
		return true
	case BulkDecisionItemActionDismissed:
		return true
	default:
		return false
	}
}

// Defines values for DecisionAction.
const (
	DecisionActionConfirmed DecisionAction = "confirmed"
	DecisionActionDismissed DecisionAction = "dismissed"
)

// Valid indicates whether the value is a known member of the DecisionAction enum.
func (e DecisionAction) Valid() bool {
	switch e {
	case DecisionActionConfirmed:
		return true
	case DecisionActionDismissed:
		return true
	default:
		return false
	}
}

// Defines values for DecisionRequestAction.
const (
	DecisionRequestActionConfirmed DecisionRequestAction = "confirmed"
	DecisionRequestActionDismissed DecisionRequestAction = "dismissed"
)

// Valid indicates whether the value is a known member of the DecisionRequestAction enum.
func (e DecisionRequestAction) Valid() bool {
	switch e {
	case DecisionRequestActionConfirmed:
		return true
	case DecisionRequestActionDismissed:
		return true
	default:
		return false
	}
}

// Defines values for ImportDetectStatus.
const (
	ImportDetectStatusCompleted ImportDetectStatus = "completed"
	ImportDetectStatusFailed    ImportDetectStatus = "failed"
	ImportDetectStatusRunning   ImportDetectStatus = "running"
)

// Valid indicates whether the value is a known member of the ImportDetectStatus enum.
func (e ImportDetectStatus) Valid() bool {
	switch e {
	case ImportDetectStatusCompleted:
		return true
	case ImportDetectStatusFailed:
		return true
	case ImportDetectStatusRunning:
		return true
	default:
		return false
	}
}

// Defines values for ImportStatus.
const (
	ImportStatusCompleted ImportStatus = "completed"
	ImportStatusFailed    ImportStatus = "failed"
	ImportStatusRunning   ImportStatus = "running"
)

// Valid indicates whether the value is a known member of the ImportStatus enum.
func (e ImportStatus) Valid() bool {
	switch e {
	case ImportStatusCompleted:
		return true
	case ImportStatusFailed:
		return true
	case ImportStatusRunning:
		return true
	default:
		return false
	}
}

// Defines values for ImportPhotoPlaceKind.
const (
	ImportPhotoPlaceKindAir      ImportPhotoPlaceKind = "air"
	ImportPhotoPlaceKindObserved ImportPhotoPlaceKind = "observed"
	ImportPhotoPlaceKindRoad     ImportPhotoPlaceKind = "road"
	ImportPhotoPlaceKindStop     ImportPhotoPlaceKind = "stop"
	ImportPhotoPlaceKindUnknown  ImportPhotoPlaceKind = "unknown"
)

// Valid indicates whether the value is a known member of the ImportPhotoPlaceKind enum.
func (e ImportPhotoPlaceKind) Valid() bool {
	switch e {
	case ImportPhotoPlaceKindAir:
		return true
	case ImportPhotoPlaceKindObserved:
		return true
	case ImportPhotoPlaceKindRoad:
		return true
	case ImportPhotoPlaceKindStop:
		return true
	case ImportPhotoPlaceKindUnknown:
		return true
	default:
		return false
	}
}

// Defines values for ImportPhotoPosSource.
const (
	ImportPhotoPosSourceExif    ImportPhotoPosSource = "exif"
	ImportPhotoPosSourceSidecar ImportPhotoPosSource = "sidecar"
)

// Valid indicates whether the value is a known member of the ImportPhotoPosSource enum.
func (e ImportPhotoPosSource) Valid() bool {
	switch e {
	case ImportPhotoPosSourceExif:
		return true
	case ImportPhotoPosSourceSidecar:
		return true
	default:
		return false
	}
}

// Defines values for ImportPhotoTimeSource.
const (
	ImportPhotoTimeSourceExifLocal  ImportPhotoTimeSource = "exif_local"
	ImportPhotoTimeSourceExifOffset ImportPhotoTimeSource = "exif_offset"
	ImportPhotoTimeSourceGps        ImportPhotoTimeSource = "gps"
	ImportPhotoTimeSourceSidecar    ImportPhotoTimeSource = "sidecar"
)

// Valid indicates whether the value is a known member of the ImportPhotoTimeSource enum.
func (e ImportPhotoTimeSource) Valid() bool {
	switch e {
	case ImportPhotoTimeSourceExifLocal:
		return true
	case ImportPhotoTimeSourceExifOffset:
		return true
	case ImportPhotoTimeSourceGps:
		return true
	case ImportPhotoTimeSourceSidecar:
		return true
	default:
		return false
	}
}

// Defines values for LegGapKind.
const (
	LegGapKindAir     LegGapKind = "air"
	LegGapKindRoad    LegGapKind = "road"
	LegGapKindUnknown LegGapKind = "unknown"
)

// Valid indicates whether the value is a known member of the LegGapKind enum.
func (e LegGapKind) Valid() bool {
	switch e {
	case LegGapKindAir:
		return true
	case LegGapKindRoad:
		return true
	case LegGapKindUnknown:
		return true
	default:
		return false
	}
}

// Defines values for LegKind.
const (
	LegKindGap      LegKind = "gap"
	LegKindObserved LegKind = "observed"
)

// Valid indicates whether the value is a known member of the LegKind enum.
func (e LegKind) Valid() bool {
	switch e {
	case LegKindGap:
		return true
	case LegKindObserved:
		return true
	default:
		return false
	}
}

// Defines values for PhotoPlaceKind.
const (
	PhotoPlaceKindAir      PhotoPlaceKind = "air"
	PhotoPlaceKindObserved PhotoPlaceKind = "observed"
	PhotoPlaceKindRoad     PhotoPlaceKind = "road"
	PhotoPlaceKindStop     PhotoPlaceKind = "stop"
	PhotoPlaceKindUnknown  PhotoPlaceKind = "unknown"
)

// Valid indicates whether the value is a known member of the PhotoPlaceKind enum.
func (e PhotoPlaceKind) Valid() bool {
	switch e {
	case PhotoPlaceKindAir:
		return true
	case PhotoPlaceKindObserved:
		return true
	case PhotoPlaceKindRoad:
		return true
	case PhotoPlaceKindStop:
		return true
	case PhotoPlaceKindUnknown:
		return true
	default:
		return false
	}
}

// Defines values for PhotoPosSource.
const (
	PhotoPosSourceExif    PhotoPosSource = "exif"
	PhotoPosSourceNone    PhotoPosSource = "none"
	PhotoPosSourceSidecar PhotoPosSource = "sidecar"
)

// Valid indicates whether the value is a known member of the PhotoPosSource enum.
func (e PhotoPosSource) Valid() bool {
	switch e {
	case PhotoPosSourceExif:
		return true
	case PhotoPosSourceNone:
		return true
	case PhotoPosSourceSidecar:
		return true
	default:
		return false
	}
}

// Defines values for PhotoTimeSource.
const (
	PhotoTimeSourceExifLocal  PhotoTimeSource = "exif_local"
	PhotoTimeSourceExifOffset PhotoTimeSource = "exif_offset"
	PhotoTimeSourceGps        PhotoTimeSource = "gps"
	PhotoTimeSourceNone       PhotoTimeSource = "none"
	PhotoTimeSourceSidecar    PhotoTimeSource = "sidecar"
)

// Valid indicates whether the value is a known member of the PhotoTimeSource enum.
func (e PhotoTimeSource) Valid() bool {
	switch e {
	case PhotoTimeSourceExifLocal:
		return true
	case PhotoTimeSourceExifOffset:
		return true
	case PhotoTimeSourceGps:
		return true
	case PhotoTimeSourceNone:
		return true
	case PhotoTimeSourceSidecar:
		return true
	default:
		return false
	}
}

// Defines values for PhotoImportFileStatus.
const (
	PhotoImportFileStatusFix             PhotoImportFileStatus = "fix"
	PhotoImportFileStatusNoPosition      PhotoImportFileStatus = "no_position"
	PhotoImportFileStatusNoTime          PhotoImportFileStatus = "no_time"
	PhotoImportFileStatusSidecarPaired   PhotoImportFileStatus = "sidecar_paired"
	PhotoImportFileStatusSidecarUnpaired PhotoImportFileStatus = "sidecar_unpaired"
	PhotoImportFileStatusUnsupported     PhotoImportFileStatus = "unsupported"
)

// Valid indicates whether the value is a known member of the PhotoImportFileStatus enum.
func (e PhotoImportFileStatus) Valid() bool {
	switch e {
	case PhotoImportFileStatusFix:
		return true
	case PhotoImportFileStatusNoPosition:
		return true
	case PhotoImportFileStatusNoTime:
		return true
	case PhotoImportFileStatusSidecarPaired:
		return true
	case PhotoImportFileStatusSidecarUnpaired:
		return true
	case PhotoImportFileStatusUnsupported:
		return true
	default:
		return false
	}
}

// Defines values for PhotoUploadResultStatus.
const (
	PhotoUploadResultStatusAccepted        PhotoUploadResultStatus = "accepted"
	PhotoUploadResultStatusDuplicate       PhotoUploadResultStatus = "duplicate"
	PhotoUploadResultStatusRejected        PhotoUploadResultStatus = "rejected"
	PhotoUploadResultStatusSidecarPaired   PhotoUploadResultStatus = "sidecar_paired"
	PhotoUploadResultStatusSidecarUnpaired PhotoUploadResultStatus = "sidecar_unpaired"
)

// Valid indicates whether the value is a known member of the PhotoUploadResultStatus enum.
func (e PhotoUploadResultStatus) Valid() bool {
	switch e {
	case PhotoUploadResultStatusAccepted:
		return true
	case PhotoUploadResultStatusDuplicate:
		return true
	case PhotoUploadResultStatusRejected:
		return true
	case PhotoUploadResultStatusSidecarPaired:
		return true
	case PhotoUploadResultStatusSidecarUnpaired:
		return true
	default:
		return false
	}
}

// BulkDecisionItem defines model for BulkDecisionItem.
type BulkDecisionItem struct {
	Action BulkDecisionItemAction `json:"action"`

	// Id Candidate id from the latest run.
	Id int64 `json:"id"`

	// Name Required, non-empty, when action is "confirmed".
	Name *string `json:"name,omitempty"`
}

// BulkDecisionItemAction defines model for BulkDecisionItem.Action.
type BulkDecisionItemAction string

// BulkDecisionRequest defines model for BulkDecisionRequest.
type BulkDecisionRequest struct {
	Decisions []BulkDecisionItem `json:"decisions"`
}

// BulkDecisionResult defines model for BulkDecisionResult.
type BulkDecisionResult struct {
	// Decided How many decisions were applied (equals the request's count).
	Decided int `json:"decided"`
}

// Candidate defines model for Candidate.
type Candidate struct {
	Days     float64   `json:"days"`
	Decision *Decision `json:"decision,omitempty"`
	Dest     LatLng    `json:"dest"`

	// DestKm Distance home → farthest place dwelt, never merely passed through.
	DestKm       int         `json:"dest_km"`
	EndTruncated bool        `json:"end_truncated"`
	Id           int64       `json:"id"`
	Modes        []ModeCount `json:"modes"`
	ObsCount     int         `json:"obs_count"`
	Repeat       int         `json:"repeat"`

	// Score Confidence 0–100 from named weighted components (weights recorded in the run's params). Ranking and decision support only — never a filter, never auto-confirmation. Absent on candidates stored before scoring existed: not scored is different information than a low score.
	Score *float64 `json:"score,omitempty"`

	// ScoreBreakdown The per-component arithmetic that reproduces `score`.
	ScoreBreakdown *[]ScoreComponent `json:"score_breakdown,omitempty"`
	SpanEnd        time.Time         `json:"span_end"`
	SpanStart      time.Time         `json:"span_start"`

	// StartTruncated The span begins at the window edge; the real journey started earlier (bug 4).
	StartTruncated bool `json:"start_truncated"`
	Stops          int  `json:"stops"`
	TrackKm        int  `json:"track_km"`
}

// CandidateList defines model for CandidateList.
type CandidateList struct {
	Candidates []Candidate `json:"candidates"`

	// OrphanedDecisions Decisions no current candidate matched. Never hidden: a parameter change may orphan a decision, and lowering it back re-matches.
	OrphanedDecisions []Decision `json:"orphaned_decisions"`
	Run               *Run       `json:"run,omitempty"`
}

// Country defines model for Country.
type Country struct {
	// IsoCode ISO 3166-1 alpha-2 where Natural Earth provides one (Kosovo's XK is user-assigned); territories without any alpha-2 carry Natural Earth's three-letter ADM0_A3 instead.
	IsoCode string `json:"iso_code"`
	Name    string `json:"name"`
}

// Decision defines model for Decision.
type Decision struct {
	Action DecisionAction `json:"action"`
	Id     int64          `json:"id"`

	// Name Present when action is confirmed.
	Name      *string   `json:"name,omitempty"`
	UpdatedAt time.Time `json:"updated_at"`
}

// DecisionAction defines model for Decision.Action.
type DecisionAction string

// DecisionRequest defines model for DecisionRequest.
type DecisionRequest struct {
	Action DecisionRequestAction `json:"action"`

	// Name Required when action is confirmed.
	Name *string `json:"name,omitempty"`
}

// DecisionRequestAction defines model for DecisionRequest.Action.
type DecisionRequestAction string

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// Health defines model for Health.
type Health struct {
	// Status Example: ok
	Status string `json:"status"`
}

// Import defines model for Import.
type Import struct {
	Activities int `json:"activities"`

	// ContentHash SHA-256 of the uploaded file, upload-path imports only — the retained file's name in the uploads directory (the photos content-hash precedent). Absent on CLI imports.
	ContentHash *string `json:"content_hash,omitempty"`

	// DetectStatus Status of the automatic detection that follows a successful upload import (phase 7 BRIEF §3D). Absent when no auto-detect was triggered (CLI imports, failed imports). A detection failure never marks the import failed — the import row describes the import.
	DetectStatus *ImportDetectStatus `json:"detect_status,omitempty"`

	// DetectedFormat The sniffer's stable format label (phone-timeline, records-json, semantic-history, …). Absent when the input was never recognised.
	DetectedFormat *string `json:"detected_format,omitempty"`

	// Error The user-facing failure message — prose, subject to rewording; never the queryable evidence.
	Error      *string   `json:"error,omitempty"`
	Id         int64     `json:"id"`
	ImportedAt time.Time `json:"imported_at"`

	// Inserted How many observations were genuinely new — the per-type counters record what the file contained; this records what the database gained. Zero on a duplicate upload ("nothing new"). Absent on rows from before this field existed.
	Inserted     *int `json:"inserted,omitempty"`
	Points       int  `json:"points"`
	RawPositions int  `json:"raw_positions"`
	Skipped      int  `json:"skipped"`

	// SourceLabel Provenance label, defaulting to the source file name.
	SourceLabel string       `json:"source_label"`
	Status      ImportStatus `json:"status"`
	Visits      int          `json:"visits"`
	WindowEnd   *time.Time   `json:"window_end,omitempty"`

	// WindowStart Optional import date window (the -from flag). Absent means unbounded.
	WindowStart *time.Time `json:"window_start,omitempty"`
}

// ImportDetectStatus Status of the automatic detection that follows a successful upload import (phase 7 BRIEF §3D). Absent when no auto-detect was triggered (CLI imports, failed imports). A detection failure never marks the import failed — the import row describes the import.
type ImportDetectStatus string

// ImportStatus defines model for Import.Status.
type ImportStatus string

// ImportList defines model for ImportList.
type ImportList struct {
	Imports []Import `json:"imports"`
}

// ImportPhoto One photo-import record (phase 11 §4D), distinct from Photo deliberately: records ride imports and are never deletable from an adventure, while attached photos ride decisions and are — one schema for both would blur what each id can do. Records exist only for usable photos, so position and instant are always present.
type ImportPhoto struct {
	DistanceFromRouteM *float64 `json:"distance_from_route_m,omitempty"`
	FarFlagged         *bool    `json:"far_flagged,omitempty"`
	Id                 int64    `json:"id"`

	// ImportId The photo import this record arrived in.
	ImportId     int64  `json:"import_id"`
	LegIndex     *int   `json:"leg_index,omitempty"`
	OriginalName string `json:"original_name"`

	// PlaceKind Same read-time placement as Photo.place_kind, against the same drawn geometry. Absent when the instant falls outside every leg and stop of the assembled journey.
	PlaceKind *ImportPhotoPlaceKind `json:"place_kind,omitempty"`
	Pos       LatLng                `json:"pos"`
	PosSource ImportPhotoPosSource  `json:"pos_source"`
	StopIndex *int                  `json:"stop_index,omitempty"`
	TakenAt   time.Time             `json:"taken_at"`

	// TakenOffsetSec Civil offset for display, seconds east of UTC.
	TakenOffsetSec int `json:"taken_offset_sec"`
	ThumbH         int `json:"thumb_h"`

	// ThumbW Thumbnail pixel width; 0 means no thumbnail (HEIC).
	ThumbW     int                   `json:"thumb_w"`
	TimeSource ImportPhotoTimeSource `json:"time_source"`
	UploadedAt time.Time             `json:"uploaded_at"`
}

// ImportPhotoPlaceKind Same read-time placement as Photo.place_kind, against the same drawn geometry. Absent when the instant falls outside every leg and stop of the assembled journey.
type ImportPhotoPlaceKind string

// ImportPhotoPosSource defines model for ImportPhoto.PosSource.
type ImportPhotoPosSource string

// ImportPhotoTimeSource defines model for ImportPhoto.TimeSource.
type ImportPhotoTimeSource string

// ImportPhotoList defines model for ImportPhotoList.
type ImportPhotoList struct {
	// Params The placement parameters that produced the derived fields (invariant 3) — photo_far_warn_m today.
	Params map[string]interface{} `json:"params"`
	Photos []ImportPhoto          `json:"photos"`
}

// ImportRejection defines model for ImportRejection.
type ImportRejection struct {
	// DetectedFormat The stable format label (zip, records-json, …) — what the file actually is, for mapping to a walkthrough anchor. Absent when the input was not recognisable at all.
	DetectedFormat *string `json:"detected_format,omitempty"`

	// Error The sniffer's actionable message — prose, rewordable.
	Error string `json:"error"`
}

// Journey defines model for Journey.
type Journey struct {
	// AirKm Chord sum over air-classified gaps — a subset of inferred_km. The endpoint chord is the great-circle distance, so it is also the arc's length. Excluded from road-distance validation. 0 for a ground journey.
	AirKm float64 `json:"air_km"`

	// Countries Countries the route's points fall in, ordered by first appearance along the journey. Derived locally by point-in-polygon against bundled Natural Earth polygons — never a network lookup. Empty when `roadbook countries` has not been run. Border-adjacent points can misattribute at 1:110m resolution; the UI labels this line as derived.
	Countries []Country `json:"countries"`

	// DivergenceFlagged True when divergence_pct exceeds the divergence_warn_pct parameter (echoed in params) in either direction. Absent whenever divergence_pct is absent. Computed server-side so the frontend renders the flag without owning the threshold.
	DivergenceFlagged *bool `json:"divergence_flagged,omitempty"`

	// DivergencePct Signed percentage by which ground_km differs from google_ground_km. Absent when Google recorded no ground distance in the window — nothing to compare is not zero divergence. A conversation starter, never a gate: unroutable gaps under-count, OSM detours over-count, and both explain themselves on the map.
	DivergencePct *float64 `json:"divergence_pct,omitempty"`

	// GoogleGroundKm Google's own activity distances minus FLYING-mode activities — the comparable side of the road validation. Air must leave both sides or neither. Mode is a guess: a flight Google mislabelled as ground inflates this figure, and the divergence flag is the tripwire that surfaces it.
	GoogleGroundKm float64 `json:"google_ground_km"`

	// GoogleKm Google's own distance figure summed over the window's activities — the independent check routed distance is validated against in phase 3. 0 when the window holds no activities.
	GoogleKm float64 `json:"google_km"`

	// GroundKm The road-comparable reconstruction: observed + routed + unknown chords. Air legs are excluded by construction.
	GroundKm     float64 `json:"ground_km"`
	InferredKm   float64 `json:"inferred_km"`
	Legs         []Leg   `json:"legs"`
	MergedPoints int     `json:"merged_points"`

	// ModeBreakdown Source-asserted per-mode distance (phase 11 §6.2): the window's activity distances summed by Google's own mode labels, ordered km-descending. These are the source's guesses (recorded failures: a 1,023 km "motorcycling" relocation, probability-0.00 modes; the pipeline itself trusts speed over mode for flight), so display keeps them visually subordinate, labels the source, and never sums them against measured geometry. Absent — not empty — when the journey's evidence carries no activities at all (photo-sourced journeys): the display states that rather than showing zeros.
	ModeBreakdown *[]ModeKm `json:"mode_breakdown,omitempty"`
	ObservedKm    float64   `json:"observed_km"`

	// Params Exactly the parameters that produced this assembly (invariant 3).
	Params        map[string]interface{} `json:"params"`
	RawPointsKept int                    `json:"raw_points_kept"`

	// RoutedKm Routed road distance summed over road legs. 0 when nothing is routed — the product is fully usable without a router.
	RoutedKm        float64 `json:"routed_km"`
	Stops           []Stop  `json:"stops"`
	TotalKm         float64 `json:"total_km"`
	TracePointsKept int     `json:"trace_points_kept"`

	// UnknownKm Chord sum over gaps still unknown after the routing cache was consulted — the visibly-unfilled remainder. A router that cannot fill a gap leaves it here by design (patchy OSM coverage is the expected case, not an error).
	UnknownKm   float64   `json:"unknown_km"`
	WindowEnd   time.Time `json:"window_end"`
	WindowStart time.Time `json:"window_start"`
}

// LatLng defines model for LatLng.
type LatLng struct {
	Lat float64 `json:"lat"`
	Lon float64 `json:"lon"`
}

// Leg defines model for Leg.
type Leg struct {
	// DistanceKm Chord sum for observed legs; endpoint chord for gaps.
	DistanceKm float64   `json:"distance_km"`
	End        time.Time `json:"end"`

	// GapKind Present only when kind is "gap". "air": the gap's implied speed (endpoint chord over duration) met the air_speed_min_kmh parameter — rendered as a great-circle arc, never routed, excluded from road-distance validation. "road": the routing cache supplied road geometry for this gap. "unknown": neither — drawn as a dashed straight line that is not a route.
	GapKind *LegGapKind `json:"gap_kind,omitempty"`
	Kind    LegKind     `json:"kind"`

	// Points An observed leg carries its full point run; a gap leg carries exactly its two endpoints.
	Points []TimedPoint `json:"points"`

	// RoutedKm The routed road distance — present only when gap_kind is "road". distance_km keeps its chord meaning regardless.
	RoutedKm *float64 `json:"routed_km,omitempty"`

	// RoutedPoints Road geometry from the routing cache — present only when gap_kind is "road". Rides alongside points (which still holds exactly the two timestamped endpoints): routed vertices have no timestamps, and are inference, not measurement.
	RoutedPoints *[]LatLng `json:"routed_points,omitempty"`
	Start        time.Time `json:"start"`
}

// LegGapKind Present only when kind is "gap". "air": the gap's implied speed (endpoint chord over duration) met the air_speed_min_kmh parameter — rendered as a great-circle arc, never routed, excluded from road-distance validation. "road": the routing cache supplied road geometry for this gap. "unknown": neither — drawn as a dashed straight line that is not a route.
type LegGapKind string

// LegKind defines model for Leg.Kind.
type LegKind string

// ModeCount defines model for ModeCount.
type ModeCount struct {
	// Mode Google's mode guess, e.g. IN_PASSENGER_VEHICLE. Unreliable at extremes.
	Mode string `json:"mode"`
	N    int    `json:"n"`
}

// ModeKm defines model for ModeKm.
type ModeKm struct {
	Km float64 `json:"km"`

	// Mode The source's own label (IN_BUS, FLYING, …), unreworded.
	Mode string `json:"mode"`
}

// NameSuggestion defines model for NameSuggestion.
type NameSuggestion struct {
	// Name Absent when there is nothing to suggest.
	Name *string `json:"name,omitempty"`

	// Source Which suggester answered — "none" for the null implementation.
	Source string `json:"source"`
}

// Photo defines model for Photo.
type Photo struct {
	// DistanceFromRouteM Point-to-polyline distance from the photo's position to the placed element's drawn geometry. Absent for place_kind "air": the arc is presentation between two endpoints, not a claimed path, so "far from it" asserts nothing.
	DistanceFromRouteM *float64 `json:"distance_from_route_m,omitempty"`

	// FarFlagged True when distance_from_route_m exceeds the photo_far_warn_m parameter (echoed in the list's params). The photo's position is a measurement — the most accurate in the project — so the flag marks a disagreement between the photo and the inferred route, not a doubt about the photo. A conversation starter, never a gate.
	FarFlagged *bool `json:"far_flagged,omitempty"`
	Id         int64 `json:"id"`

	// LegIndex Index into the journey's legs. Present for leg place kinds.
	LegIndex     *int   `json:"leg_index,omitempty"`
	OriginalName string `json:"original_name"`

	// PlaceKind Which element of the journey held this photo's instant — and therefore which drawn geometry distance_from_route_m was measured against (BRIEF §3G) - an observed leg's measured points, a road gap's routed polyline, an unknown gap's chord, or a stop's location. Absent when the photo is unplaced: no position, no resolved instant, or an instant outside every leg and stop. Derived at read time, never stored — re-detection re-places photos automatically.
	PlaceKind *PhotoPlaceKind `json:"place_kind,omitempty"`
	Pos       *LatLng         `json:"pos,omitempty"`

	// PosSource Which reading produced pos (BRIEF §3D) — the camera's own GPS block, or Google's copy from the Takeout sidecar. "none": no position; the photo appears in the strip but not on the map.
	PosSource PhotoPosSource `json:"pos_source"`

	// StopIndex Index into the journey's stops. Present when place_kind is "stop".
	StopIndex *int `json:"stop_index,omitempty"`

	// TakenAt The resolved capture instant. Absent when no rung of the time ladder resolved (time_source "none") — the photo is stored and shown, but unplaced on map and timeline.
	TakenAt *time.Time `json:"taken_at,omitempty"`

	// TakenOffsetSec Civil offset for display, seconds east of UTC. Present exactly when taken_at is.
	TakenOffsetSec *int `json:"taken_offset_sec,omitempty"`
	ThumbH         int  `json:"thumb_h"`

	// ThumbW Thumbnail pixel width, post-orientation.
	ThumbW int `json:"thumb_w"`

	// TimeSource Which rung of the resolution ladder produced taken_at (BRIEF §3E), strongest first — the GPS receiver's own UTC clock, the explicit EXIF offset tag, the Takeout sidecar's epoch, or the wall clock interpreted in the adventure's own offset (stated as the weakest rung; wrong by the zone difference on multi-zone adventures).
	TimeSource PhotoTimeSource `json:"time_source"`
	UploadedAt time.Time       `json:"uploaded_at"`
}

// PhotoPlaceKind Which element of the journey held this photo's instant — and therefore which drawn geometry distance_from_route_m was measured against (BRIEF §3G) - an observed leg's measured points, a road gap's routed polyline, an unknown gap's chord, or a stop's location. Absent when the photo is unplaced: no position, no resolved instant, or an instant outside every leg and stop. Derived at read time, never stored — re-detection re-places photos automatically.
type PhotoPlaceKind string

// PhotoPosSource Which reading produced pos (BRIEF §3D) — the camera's own GPS block, or Google's copy from the Takeout sidecar. "none": no position; the photo appears in the strip but not on the map.
type PhotoPosSource string

// PhotoTimeSource Which rung of the resolution ladder produced taken_at (BRIEF §3E), strongest first — the GPS receiver's own UTC clock, the explicit EXIF offset tag, the Takeout sidecar's epoch, or the wall clock interpreted in the adventure's own offset (stated as the weakest rung; wrong by the zone difference on multi-zone adventures).
type PhotoTimeSource string

// PhotoImportFile defines model for PhotoImportFile.
type PhotoImportFile struct {
	File string `json:"file"`

	// Message Prose for rejected files — rewordable, never the label.
	Message *string `json:"message,omitempty"`

	// Status What this file contributed. "fix" — a position fix was extracted (with a photo record, and a thumbnail where decodable); "no_position"/"no_time" — a recognised photo carrying no usable reading (photos are stored only when they place something); sidecar verdicts mirror the phase-4 upload; "unsupported" carries the sniffer's actionable message.
	Status PhotoImportFileStatus `json:"status"`
}

// PhotoImportFileStatus What this file contributed. "fix" — a position fix was extracted (with a photo record, and a thumbnail where decodable); "no_position"/"no_time" — a recognised photo carrying no usable reading (photos are stored only when they place something); sidecar verdicts mirror the phase-4 upload; "unsupported" carries the sniffer's actionable message.
type PhotoImportFileStatus string

// PhotoImportResult defines model for PhotoImportResult.
type PhotoImportResult struct {
	Files  []PhotoImportFile `json:"files"`
	Import Import            `json:"import"`
}

// PhotoList defines model for PhotoList.
type PhotoList struct {
	// Params The placement parameters that produced the derived fields (invariant 3) — photo_far_warn_m today.
	Params map[string]interface{} `json:"params"`
	Photos []Photo                `json:"photos"`
}

// PhotoUploadResult defines model for PhotoUploadResult.
type PhotoUploadResult struct {
	// File The uploaded filename this result is about.
	File string `json:"file"`

	// PairedWith The image filename a sidecar was applied to.
	PairedWith *string `json:"paired_with,omitempty"`
	Photo      *Photo  `json:"photo,omitempty"`

	// Reason The actionable rejection message. Present when rejected.
	Reason *string `json:"reason,omitempty"`

	// Status accepted — stored, thumbnail written. duplicate — identical bytes already stored (the existing photo is returned). rejected — not a supported photo; reason says what it actually is and what to do. sidecar_paired — a Takeout JSON consumed as metadata for paired_with. sidecar_unpaired — a sidecar naming no image in this upload; nothing stored.
	Status PhotoUploadResultStatus `json:"status"`
}

// PhotoUploadResultStatus accepted — stored, thumbnail written. duplicate — identical bytes already stored (the existing photo is returned). rejected — not a supported photo; reason says what it actually is and what to do. sidecar_paired — a Takeout JSON consumed as metadata for paired_with. sidecar_unpaired — a sidecar naming no image in this upload; nothing stored.
type PhotoUploadResultStatus string

// PhotoUploadResults defines model for PhotoUploadResults.
type PhotoUploadResults struct {
	Results []PhotoUploadResult `json:"results"`
}

// Run defines model for Run.
type Run struct {
	Id              int64 `json:"id"`
	OutliersDropped int   `json:"outliers_dropped"`

	// Params Exactly the parameters that produced this run (invariant 3).
	Params map[string]interface{} `json:"params"`
	RanAt  time.Time              `json:"ran_at"`
}

// ScoreComponent defines model for ScoreComponent.
type ScoreComponent struct {
	// Contribution Points contributed to the 0–100 score; contributions sum to it.
	Contribution float64 `json:"contribution"`

	// Name e.g. distance_from_home, destination_dwell.
	Name string `json:"name"`

	// Normalized Raw scaled against its saturation anchor, clamped to [0,1].
	Normalized float64 `json:"normalized"`

	// Present False when the component could not be computed; its weight was redistributed across the rest, never scored as zero.
	Present bool `json:"present"`

	// Raw Measured value in `unit`; 0 when not present.
	Raw  float64 `json:"raw"`
	Unit string  `json:"unit"`

	// Weight Configured weight, before any redistribution.
	Weight float64 `json:"weight"`
}

// Stop defines model for Stop.
type Stop struct {
	// DisplacementKm First-to-last straight line during the halt, not path sum.
	DisplacementKm float64   `json:"displacement_km"`
	End            time.Time `json:"end"`
	Loc            LatLng    `json:"loc"`
	Points         int       `json:"points"`
	Start          time.Time `json:"start"`
}

// TimedPoint defines model for TimedPoint.
type TimedPoint struct {
	Lat float64   `json:"lat"`
	Lon float64   `json:"lon"`
	T   time.Time `json:"t"`
}

// UploadCandidatePhotosMultipartBody defines parameters for UploadCandidatePhotos.
type UploadCandidatePhotosMultipartBody struct {
	Files *[]openapi_types.File `json:"files,omitempty"`
}

// UploadImportMultipartBody defines parameters for UploadImport.
type UploadImportMultipartBody struct {
	// File The Timeline export.
	File openapi_types.File `json:"file"`

	// Label Provenance label; defaults to the uploaded file's name (the source_label convention).
	Label *string `json:"label,omitempty"`
}

// UploadPhotoImportMultipartBody defines parameters for UploadPhotoImport.
type UploadPhotoImportMultipartBody struct {
	// File Photos and sidecars; repeatable.
	File []openapi_types.File `json:"file"`

	// Label Provenance label; defaults to "photo upload".
	Label *string `json:"label,omitempty"`
}

// DecideCandidatesBulkJSONRequestBody defines body for DecideCandidatesBulk for application/json ContentType.
type DecideCandidatesBulkJSONRequestBody = BulkDecisionRequest

// DecideCandidateJSONRequestBody defines body for DecideCandidate for application/json ContentType.
type DecideCandidateJSONRequestBody = DecisionRequest

// UploadCandidatePhotosMultipartRequestBody defines body for UploadCandidatePhotos for multipart/form-data ContentType.
type UploadCandidatePhotosMultipartRequestBody UploadCandidatePhotosMultipartBody

// UploadImportMultipartRequestBody defines body for UploadImport for multipart/form-data ContentType.
type UploadImportMultipartRequestBody UploadImportMultipartBody

// UploadPhotoImportMultipartRequestBody defines body for UploadPhotoImport for multipart/form-data ContentType.
type UploadPhotoImportMultipartRequestBody UploadPhotoImportMultipartBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListCandidates The latest detection run's candidates, with decision state attached
	// (GET /candidates)
	ListCandidates(w http.ResponseWriter, r *http.Request)
	// DecideCandidatesBulk Decide several candidates in one atomic request
	// (POST /candidates/decisions)
	DecideCandidatesBulk(w http.ResponseWriter, r *http.Request)
	// DecideCandidate Confirm or dismiss a candidate
	// (POST /candidates/{id}/decision)
	DecideCandidate(w http.ResponseWriter, r *http.Request, id int64)
	// ListCandidateImportPhotos Photo-import records whose capture falls in this candidate's span
	// (GET /candidates/{id}/import-photos)
	ListCandidateImportPhotos(w http.ResponseWriter, r *http.Request, id int64)
	// GetCandidateJourney The journey reconstruction for a candidate of the latest run
	// (GET /candidates/{id}/journey)
	GetCandidateJourney(w http.ResponseWriter, r *http.Request, id int64)
	// SuggestCandidateName A proposed name for the candidate's adventure
	// (GET /candidates/{id}/name-suggestion)
	SuggestCandidateName(w http.ResponseWriter, r *http.Request, id int64)
	// ListCandidatePhotos The photos of a candidate's confirmed adventure
	// (GET /candidates/{id}/photos)
	ListCandidatePhotos(w http.ResponseWriter, r *http.Request, id int64)
	// UploadCandidatePhotos Upload photos (and Takeout sidecars) to a confirmed adventure
	// (POST /candidates/{id}/photos)
	UploadCandidatePhotos(w http.ResponseWriter, r *http.Request, id int64)
	// GetHealth Readiness check
	// (GET /healthz)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// GetImportPhotoThumbnail The stored thumbnail of a photo-import record
	// (GET /import-photos/{id}/thumbnail)
	GetImportPhotoThumbnail(w http.ResponseWriter, r *http.Request, id int64)
	// ListImports Every import attempt, newest first
	// (GET /imports)
	ListImports(w http.ResponseWriter, r *http.Request)
	// UploadImport Upload a Timeline export and import it
	// (POST /imports)
	UploadImport(w http.ResponseWriter, r *http.Request)
	// UploadPhotoImport Upload a batch of photos as an import source
	// (POST /imports/photos)
	UploadPhotoImport(w http.ResponseWriter, r *http.Request)
	// GetImport One import attempt, by id
	// (GET /imports/{id})
	GetImport(w http.ResponseWriter, r *http.Request, id int64)
	// DeletePhoto Delete one photo
	// (DELETE /photos/{id})
	DeletePhoto(w http.ResponseWriter, r *http.Request, id int64)
	// GetPhotoThumbnail The stored thumbnail image
	// (GET /photos/{id}/thumbnail)
	GetPhotoThumbnail(w http.ResponseWriter, r *http.Request, id int64)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListCandidates operation middleware
func (siw *ServerInterfaceWrapper) ListCandidates(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCandidates(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DecideCandidatesBulk operation middleware
func (siw *ServerInterfaceWrapper) DecideCandidatesBulk(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DecideCandidatesBulk(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DecideCandidate operation middleware
func (siw *ServerInterfaceWrapper) DecideCandidate(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DecideCandidate(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListCandidateImportPhotos operation middleware
func (siw *ServerInterfaceWrapper) ListCandidateImportPhotos(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCandidateImportPhotos(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCandidateJourney operation middleware
func (siw *ServerInterfaceWrapper) GetCandidateJourney(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCandidateJourney(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SuggestCandidateName operation middleware
func (siw *ServerInterfaceWrapper) SuggestCandidateName(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SuggestCandidateName(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListCandidatePhotos operation middleware
func (siw *ServerInterfaceWrapper) ListCandidatePhotos(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCandidatePhotos(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UploadCandidatePhotos operation middleware
func (siw *ServerInterfaceWrapper) UploadCandidatePhotos(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UploadCandidatePhotos(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetImportPhotoThumbnail operation middleware
func (siw *ServerInterfaceWrapper) GetImportPhotoThumbnail(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetImportPhotoThumbnail(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListImports operation middleware
func (siw *ServerInterfaceWrapper) ListImports(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListImports(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UploadImport operation middleware
func (siw *ServerInterfaceWrapper) UploadImport(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UploadImport(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UploadPhotoImport operation middleware
func (siw *ServerInterfaceWrapper) UploadPhotoImport(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UploadPhotoImport(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetImport operation middleware
func (siw *ServerInterfaceWrapper) GetImport(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetImport(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeletePhoto operation middleware
func (siw *ServerInterfaceWrapper) DeletePhoto(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeletePhoto(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPhotoThumbnail operation middleware
func (siw *ServerInterfaceWrapper) GetPhotoThumbnail(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPhotoThumbnail(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/healthz", wrapper.GetHealth)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/imports", wrapper.ListImports)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/imports", wrapper.UploadImport)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/imports/photos", wrapper.UploadPhotoImport)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/imports/{id}", wrapper.GetImport)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/candidates", wrapper.ListCandidates)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/candidates/decisions", wrapper.DecideCandidatesBulk)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/candidates/{id}/journey", wrapper.GetCandidateJourney)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/candidates/{id}/name-suggestion", wrapper.SuggestCandidateName)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/candidates/{id}/decision", wrapper.DecideCandidate)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/candidates/{id}/photos", wrapper.ListCandidatePhotos)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/candidates/{id}/photos", wrapper.UploadCandidatePhotos)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/candidates/{id}/import-photos", wrapper.ListCandidateImportPhotos)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/import-photos/{id}/thumbnail", wrapper.GetImportPhotoThumbnail)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/photos/{id}/thumbnail", wrapper.GetPhotoThumbnail)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/photos/{id}", wrapper.DeletePhoto)

	return m
}

type ListCandidatesRequestObject struct {
}

type ListCandidatesResponseObject interface {
	VisitListCandidatesResponse(w http.ResponseWriter) error
}

type ListCandidates200JSONResponse CandidateList

func (response ListCandidates200JSONResponse) VisitListCandidatesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type DecideCandidatesBulkRequestObject struct {
	Body *DecideCandidatesBulkJSONRequestBody
}

type DecideCandidatesBulkResponseObject interface {
	VisitDecideCandidatesBulkResponse(w http.ResponseWriter) error
}

type DecideCandidatesBulk200JSONResponse BulkDecisionResult

func (response DecideCandidatesBulk200JSONResponse) VisitDecideCandidatesBulkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type DecideCandidatesBulk400JSONResponse Error

func (response DecideCandidatesBulk400JSONResponse) VisitDecideCandidatesBulkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type DecideCandidatesBulk404JSONResponse Error

func (response DecideCandidatesBulk404JSONResponse) VisitDecideCandidatesBulkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DecideCandidateRequestObject struct {
	Id   int64 `json:"id"`
	Body *DecideCandidateJSONRequestBody
}

type DecideCandidateResponseObject interface {
	VisitDecideCandidateResponse(w http.ResponseWriter) error
}

type DecideCandidate200JSONResponse Decision

func (response DecideCandidate200JSONResponse) VisitDecideCandidateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type DecideCandidate400JSONResponse Error

func (response DecideCandidate400JSONResponse) VisitDecideCandidateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type DecideCandidate404JSONResponse Error

func (response DecideCandidate404JSONResponse) VisitDecideCandidateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListCandidateImportPhotosRequestObject struct {
	Id int64 `json:"id"`
}

type ListCandidateImportPhotosResponseObject interface {
	VisitListCandidateImportPhotosResponse(w http.ResponseWriter) error
}

type ListCandidateImportPhotos200JSONResponse ImportPhotoList

func (response ListCandidateImportPhotos200JSONResponse) VisitListCandidateImportPhotosResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListCandidateImportPhotos404JSONResponse Error

func (response ListCandidateImportPhotos404JSONResponse) VisitListCandidateImportPhotosResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetCandidateJourneyRequestObject struct {
	Id int64 `json:"id"`
}

type GetCandidateJourneyResponseObject interface {
	VisitGetCandidateJourneyResponse(w http.ResponseWriter) error
}

type GetCandidateJourney200JSONResponse Journey

func (response GetCandidateJourney200JSONResponse) VisitGetCandidateJourneyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetCandidateJourney404JSONResponse Error

func (response GetCandidateJourney404JSONResponse) VisitGetCandidateJourneyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type SuggestCandidateNameRequestObject struct {
	Id int64 `json:"id"`
}

type SuggestCandidateNameResponseObject interface {
	VisitSuggestCandidateNameResponse(w http.ResponseWriter) error
}

type SuggestCandidateName200JSONResponse NameSuggestion

func (response SuggestCandidateName200JSONResponse) VisitSuggestCandidateNameResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SuggestCandidateName404JSONResponse Error

func (response SuggestCandidateName404JSONResponse) VisitSuggestCandidateNameResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type SuggestCandidateName502JSONResponse Error

func (response SuggestCandidateName502JSONResponse) VisitSuggestCandidateNameResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(502)
	_, err := buf.WriteTo(w)
	return err
}

type ListCandidatePhotosRequestObject struct {
	Id int64 `json:"id"`
}

type ListCandidatePhotosResponseObject interface {
	VisitListCandidatePhotosResponse(w http.ResponseWriter) error
}

type ListCandidatePhotos200JSONResponse PhotoList

func (response ListCandidatePhotos200JSONResponse) VisitListCandidatePhotosResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListCandidatePhotos404JSONResponse Error

func (response ListCandidatePhotos404JSONResponse) VisitListCandidatePhotosResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListCandidatePhotos409JSONResponse Error

func (response ListCandidatePhotos409JSONResponse) VisitListCandidatePhotosResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type UploadCandidatePhotosRequestObject struct {
	Id   int64 `json:"id"`
	Body *multipart.Reader
}

type UploadCandidatePhotosResponseObject interface {
	VisitUploadCandidatePhotosResponse(w http.ResponseWriter) error
}

type UploadCandidatePhotos200JSONResponse PhotoUploadResults

func (response UploadCandidatePhotos200JSONResponse) VisitUploadCandidatePhotosResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UploadCandidatePhotos404JSONResponse Error

func (response UploadCandidatePhotos404JSONResponse) VisitUploadCandidatePhotosResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UploadCandidatePhotos409JSONResponse Error

func (response UploadCandidatePhotos409JSONResponse) VisitUploadCandidatePhotosResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse Health

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealth503JSONResponse Error

func (response GetHealth503JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetImportPhotoThumbnailRequestObject struct {
	Id int64 `json:"id"`
}

type GetImportPhotoThumbnailResponseObject interface {
	VisitGetImportPhotoThumbnailResponse(w http.ResponseWriter) error
}

type GetImportPhotoThumbnail200ImagejpegResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response GetImportPhotoThumbnail200ImagejpegResponse) VisitGetImportPhotoThumbnailResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "image/jpeg")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetImportPhotoThumbnail404JSONResponse Error

func (response GetImportPhotoThumbnail404JSONResponse) VisitGetImportPhotoThumbnailResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListImportsRequestObject struct {
}

type ListImportsResponseObject interface {
	VisitListImportsResponse(w http.ResponseWriter) error
}

type ListImports200JSONResponse ImportList

func (response ListImports200JSONResponse) VisitListImportsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UploadImportRequestObject struct {
	Body *multipart.Reader
}

type UploadImportResponseObject interface {
	VisitUploadImportResponse(w http.ResponseWriter) error
}

type UploadImport202JSONResponse Import

func (response UploadImport202JSONResponse) VisitUploadImportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)
	_, err := buf.WriteTo(w)
	return err
}

type UploadImport400JSONResponse ImportRejection

func (response UploadImport400JSONResponse) VisitUploadImportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UploadImport409JSONResponse Error

func (response UploadImport409JSONResponse) VisitUploadImportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type UploadImport413JSONResponse Error

func (response UploadImport413JSONResponse) VisitUploadImportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type UploadPhotoImportRequestObject struct {
	Body *multipart.Reader
}

type UploadPhotoImportResponseObject interface {
	VisitUploadPhotoImportResponse(w http.ResponseWriter) error
}

type UploadPhotoImport202JSONResponse PhotoImportResult

func (response UploadPhotoImport202JSONResponse) VisitUploadPhotoImportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)
	_, err := buf.WriteTo(w)
	return err
}

type UploadPhotoImport400JSONResponse Error

func (response UploadPhotoImport400JSONResponse) VisitUploadPhotoImportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UploadPhotoImport409JSONResponse Error

func (response UploadPhotoImport409JSONResponse) VisitUploadPhotoImportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type GetImportRequestObject struct {
	Id int64 `json:"id"`
}

type GetImportResponseObject interface {
	VisitGetImportResponse(w http.ResponseWriter) error
}

type GetImport200JSONResponse Import

func (response GetImport200JSONResponse) VisitGetImportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetImport404JSONResponse Error

func (response GetImport404JSONResponse) VisitGetImportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeletePhotoRequestObject struct {
	Id int64 `json:"id"`
}

type DeletePhotoResponseObject interface {
	VisitDeletePhotoResponse(w http.ResponseWriter) error
}

type DeletePhoto204Response struct {
}

func (response DeletePhoto204Response) VisitDeletePhotoResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeletePhoto404JSONResponse Error

func (response DeletePhoto404JSONResponse) VisitDeletePhotoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetPhotoThumbnailRequestObject struct {
	Id int64 `json:"id"`
}

type GetPhotoThumbnailResponseObject interface {
	VisitGetPhotoThumbnailResponse(w http.ResponseWriter) error
}

type GetPhotoThumbnail200ImagejpegResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response GetPhotoThumbnail200ImagejpegResponse) VisitGetPhotoThumbnailResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "image/jpeg")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetPhotoThumbnail404JSONResponse Error

func (response GetPhotoThumbnail404JSONResponse) VisitGetPhotoThumbnailResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// ListCandidates The latest detection run's candidates, with decision state attached
	// (GET /candidates)
	ListCandidates(ctx context.Context, request ListCandidatesRequestObject) (ListCandidatesResponseObject, error)
	// DecideCandidatesBulk Decide several candidates in one atomic request
	// (POST /candidates/decisions)
	DecideCandidatesBulk(ctx context.Context, request DecideCandidatesBulkRequestObject) (DecideCandidatesBulkResponseObject, error)
	// DecideCandidate Confirm or dismiss a candidate
	// (POST /candidates/{id}/decision)
	DecideCandidate(ctx context.Context, request DecideCandidateRequestObject) (DecideCandidateResponseObject, error)
	// ListCandidateImportPhotos Photo-import records whose capture falls in this candidate's span
	// (GET /candidates/{id}/import-photos)
	ListCandidateImportPhotos(ctx context.Context, request ListCandidateImportPhotosRequestObject) (ListCandidateImportPhotosResponseObject, error)
	// GetCandidateJourney The journey reconstruction for a candidate of the latest run
	// (GET /candidates/{id}/journey)
	GetCandidateJourney(ctx context.Context, request GetCandidateJourneyRequestObject) (GetCandidateJourneyResponseObject, error)
	// SuggestCandidateName A proposed name for the candidate's adventure
	// (GET /candidates/{id}/name-suggestion)
	SuggestCandidateName(ctx context.Context, request SuggestCandidateNameRequestObject) (SuggestCandidateNameResponseObject, error)
	// ListCandidatePhotos The photos of a candidate's confirmed adventure
	// (GET /candidates/{id}/photos)
	ListCandidatePhotos(ctx context.Context, request ListCandidatePhotosRequestObject) (ListCandidatePhotosResponseObject, error)
	// UploadCandidatePhotos Upload photos (and Takeout sidecars) to a confirmed adventure
	// (POST /candidates/{id}/photos)
	UploadCandidatePhotos(ctx context.Context, request UploadCandidatePhotosRequestObject) (UploadCandidatePhotosResponseObject, error)
	// GetHealth Readiness check
	// (GET /healthz)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// GetImportPhotoThumbnail The stored thumbnail of a photo-import record
	// (GET /import-photos/{id}/thumbnail)
	GetImportPhotoThumbnail(ctx context.Context, request GetImportPhotoThumbnailRequestObject) (GetImportPhotoThumbnailResponseObject, error)
	// ListImports Every import attempt, newest first
	// (GET /imports)
	ListImports(ctx context.Context, request ListImportsRequestObject) (ListImportsResponseObject, error)
	// UploadImport Upload a Timeline export and import it
	// (POST /imports)
	UploadImport(ctx context.Context, request UploadImportRequestObject) (UploadImportResponseObject, error)
	// UploadPhotoImport Upload a batch of photos as an import source
	// (POST /imports/photos)
	UploadPhotoImport(ctx context.Context, request UploadPhotoImportRequestObject) (UploadPhotoImportResponseObject, error)
	// GetImport One import attempt, by id
	// (GET /imports/{id})
	GetImport(ctx context.Context, request GetImportRequestObject) (GetImportResponseObject, error)
	// DeletePhoto Delete one photo
	// (DELETE /photos/{id})
	DeletePhoto(ctx context.Context, request DeletePhotoRequestObject) (DeletePhotoResponseObject, error)
	// GetPhotoThumbnail The stored thumbnail image
	// (GET /photos/{id}/thumbnail)
	GetPhotoThumbnail(ctx context.Context, request GetPhotoThumbnailRequestObject) (GetPhotoThumbnailResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListCandidates operation middleware
func (sh *strictHandler) ListCandidates(w http.ResponseWriter, r *http.Request) {
	var request ListCandidatesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListCandidates(ctx, request.(ListCandidatesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListCandidates")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListCandidatesResponseObject); ok {
		if err := validResponse.VisitListCandidatesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DecideCandidatesBulk operation middleware
func (sh *strictHandler) DecideCandidatesBulk(w http.ResponseWriter, r *http.Request) {
	var request DecideCandidatesBulkRequestObject

	var body DecideCandidatesBulkJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DecideCandidatesBulk(ctx, request.(DecideCandidatesBulkRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DecideCandidatesBulk")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DecideCandidatesBulkResponseObject); ok {
		if err := validResponse.VisitDecideCandidatesBulkResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DecideCandidate operation middleware
func (sh *strictHandler) DecideCandidate(w http.ResponseWriter, r *http.Request, id int64) {
	var request DecideCandidateRequestObject

	request.Id = id

	var body DecideCandidateJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DecideCandidate(ctx, request.(DecideCandidateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DecideCandidate")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DecideCandidateResponseObject); ok {
		if err := validResponse.VisitDecideCandidateResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListCandidateImportPhotos operation middleware
func (sh *strictHandler) ListCandidateImportPhotos(w http.ResponseWriter, r *http.Request, id int64) {
	var request ListCandidateImportPhotosRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListCandidateImportPhotos(ctx, request.(ListCandidateImportPhotosRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListCandidateImportPhotos")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListCandidateImportPhotosResponseObject); ok {
		if err := validResponse.VisitListCandidateImportPhotosResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetCandidateJourney operation middleware
func (sh *strictHandler) GetCandidateJourney(w http.ResponseWriter, r *http.Request, id int64) {
	var request GetCandidateJourneyRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetCandidateJourney(ctx, request.(GetCandidateJourneyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCandidateJourney")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetCandidateJourneyResponseObject); ok {
		if err := validResponse.VisitGetCandidateJourneyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SuggestCandidateName operation middleware
func (sh *strictHandler) SuggestCandidateName(w http.ResponseWriter, r *http.Request, id int64) {
	var request SuggestCandidateNameRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SuggestCandidateName(ctx, request.(SuggestCandidateNameRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SuggestCandidateName")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SuggestCandidateNameResponseObject); ok {
		if err := validResponse.VisitSuggestCandidateNameResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListCandidatePhotos operation middleware
func (sh *strictHandler) ListCandidatePhotos(w http.ResponseWriter, r *http.Request, id int64) {
	var request ListCandidatePhotosRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListCandidatePhotos(ctx, request.(ListCandidatePhotosRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListCandidatePhotos")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListCandidatePhotosResponseObject); ok {
		if err := validResponse.VisitListCandidatePhotosResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UploadCandidatePhotos operation middleware
func (sh *strictHandler) UploadCandidatePhotos(w http.ResponseWriter, r *http.Request, id int64) {
	var request UploadCandidatePhotosRequestObject

	request.Id = id

	if reader, err := r.MultipartReader(); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode multipart body: %w", err))
		return
	} else {
		request.Body = reader
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UploadCandidatePhotos(ctx, request.(UploadCandidatePhotosRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UploadCandidatePhotos")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UploadCandidatePhotosResponseObject); ok {
		if err := validResponse.VisitUploadCandidatePhotosResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetImportPhotoThumbnail operation middleware
func (sh *strictHandler) GetImportPhotoThumbnail(w http.ResponseWriter, r *http.Request, id int64) {
	var request GetImportPhotoThumbnailRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetImportPhotoThumbnail(ctx, request.(GetImportPhotoThumbnailRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetImportPhotoThumbnail")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetImportPhotoThumbnailResponseObject); ok {
		if err := validResponse.VisitGetImportPhotoThumbnailResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListImports operation middleware
func (sh *strictHandler) ListImports(w http.ResponseWriter, r *http.Request) {
	var request ListImportsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListImports(ctx, request.(ListImportsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListImports")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListImportsResponseObject); ok {
		if err := validResponse.VisitListImportsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UploadImport operation middleware
func (sh *strictHandler) UploadImport(w http.ResponseWriter, r *http.Request) {
	var request UploadImportRequestObject

	if reader, err := r.MultipartReader(); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode multipart body: %w", err))
		return
	} else {
		request.Body = reader
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UploadImport(ctx, request.(UploadImportRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UploadImport")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UploadImportResponseObject); ok {
		if err := validResponse.VisitUploadImportResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UploadPhotoImport operation middleware
func (sh *strictHandler) UploadPhotoImport(w http.ResponseWriter, r *http.Request) {
	var request UploadPhotoImportRequestObject

	if reader, err := r.MultipartReader(); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode multipart body: %w", err))
		return
	} else {
		request.Body = reader
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UploadPhotoImport(ctx, request.(UploadPhotoImportRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UploadPhotoImport")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UploadPhotoImportResponseObject); ok {
		if err := validResponse.VisitUploadPhotoImportResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetImport operation middleware
func (sh *strictHandler) GetImport(w http.ResponseWriter, r *http.Request, id int64) {
	var request GetImportRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetImport(ctx, request.(GetImportRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetImport")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetImportResponseObject); ok {
		if err := validResponse.VisitGetImportResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeletePhoto operation middleware
func (sh *strictHandler) DeletePhoto(w http.ResponseWriter, r *http.Request, id int64) {
	var request DeletePhotoRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeletePhoto(ctx, request.(DeletePhotoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeletePhoto")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeletePhotoResponseObject); ok {
		if err := validResponse.VisitDeletePhotoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPhotoThumbnail operation middleware
func (sh *strictHandler) GetPhotoThumbnail(w http.ResponseWriter, r *http.Request, id int64) {
	var request GetPhotoThumbnailRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetPhotoThumbnail(ctx, request.(GetPhotoThumbnailRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPhotoThumbnail")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPhotoThumbnailResponseObject); ok {
		if err := validResponse.VisitGetPhotoThumbnailResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
