//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for DecisionAction.
const (
	DecisionActionConfirmed DecisionAction = "confirmed"
	DecisionActionDismissed DecisionAction = "dismissed"
)

// Valid indicates whether the value is a known member of the DecisionAction enum.
func (e DecisionAction) Valid() bool {
	switch e {
	case DecisionActionConfirmed:
		return true
	case DecisionActionDismissed:
		return true
	default:
		return false
	}
}

// Defines values for DecisionRequestAction.
const (
	DecisionRequestActionConfirmed DecisionRequestAction = "confirmed"
	DecisionRequestActionDismissed DecisionRequestAction = "dismissed"
)

// Valid indicates whether the value is a known member of the DecisionRequestAction enum.
func (e DecisionRequestAction) Valid() bool {
	switch e {
	case DecisionRequestActionConfirmed:
		return true
	case DecisionRequestActionDismissed:
		return true
	default:
		return false
	}
}

// Defines values for LegGapKind.
const (
	Air     LegGapKind = "air"
	Road    LegGapKind = "road"
	Unknown LegGapKind = "unknown"
)

// Valid indicates whether the value is a known member of the LegGapKind enum.
func (e LegGapKind) Valid() bool {
	switch e {
	case Air:
		return true
	case Road:
		return true
	case Unknown:
		return true
	default:
		return false
	}
}

// Defines values for LegKind.
const (
	Gap      LegKind = "gap"
	Observed LegKind = "observed"
)

// Valid indicates whether the value is a known member of the LegKind enum.
func (e LegKind) Valid() bool {
	switch e {
	case Gap:
		return true
	case Observed:
		return true
	default:
		return false
	}
}

// Candidate defines model for Candidate.
type Candidate struct {
	Days     float64   `json:"days"`
	Decision *Decision `json:"decision,omitempty"`
	Dest     LatLng    `json:"dest"`

	// DestKm Distance home → farthest place dwelt, never merely passed through.
	DestKm       int         `json:"dest_km"`
	EndTruncated bool        `json:"end_truncated"`
	Id           int64       `json:"id"`
	Modes        []ModeCount `json:"modes"`
	ObsCount     int         `json:"obs_count"`
	Repeat       int         `json:"repeat"`

	// Score Confidence 0–100 from named weighted components (weights recorded in the run's params). Ranking and decision support only — never a filter, never auto-confirmation. Absent on candidates stored before scoring existed: not scored is different information than a low score.
	Score *float64 `json:"score,omitempty"`

	// ScoreBreakdown The per-component arithmetic that reproduces `score`.
	ScoreBreakdown *[]ScoreComponent `json:"score_breakdown,omitempty"`
	SpanEnd        time.Time         `json:"span_end"`
	SpanStart      time.Time         `json:"span_start"`

	// StartTruncated The span begins at the window edge; the real journey started earlier (bug 4).
	StartTruncated bool `json:"start_truncated"`
	Stops          int  `json:"stops"`
	TrackKm        int  `json:"track_km"`
}

// CandidateList defines model for CandidateList.
type CandidateList struct {
	Candidates []Candidate `json:"candidates"`

	// OrphanedDecisions Decisions no current candidate matched. Never hidden: a parameter change may orphan a decision, and lowering it back re-matches.
	OrphanedDecisions []Decision `json:"orphaned_decisions"`
	Run               *Run       `json:"run,omitempty"`
}

// Country defines model for Country.
type Country struct {
	// IsoCode ISO 3166-1 alpha-2 where Natural Earth provides one (Kosovo's XK is user-assigned); territories without any alpha-2 carry Natural Earth's three-letter ADM0_A3 instead.
	IsoCode string `json:"iso_code"`
	Name    string `json:"name"`
}

// Decision defines model for Decision.
type Decision struct {
	Action DecisionAction `json:"action"`
	Id     int64          `json:"id"`

	// Name Present when action is confirmed.
	Name      *string   `json:"name,omitempty"`
	UpdatedAt time.Time `json:"updated_at"`
}

// DecisionAction defines model for Decision.Action.
type DecisionAction string

// DecisionRequest defines model for DecisionRequest.
type DecisionRequest struct {
	Action DecisionRequestAction `json:"action"`

	// Name Required when action is confirmed.
	Name *string `json:"name,omitempty"`
}

// DecisionRequestAction defines model for DecisionRequest.Action.
type DecisionRequestAction string

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// Health defines model for Health.
type Health struct {
	// Status Example: ok
	Status string `json:"status"`
}

// Journey defines model for Journey.
type Journey struct {
	// Countries Countries the route's points fall in, ordered by first appearance along the journey. Derived locally by point-in-polygon against bundled Natural Earth polygons — never a network lookup. Empty when `roadbook countries` has not been run. Border-adjacent points can misattribute at 1:110m resolution; the UI labels this line as derived.
	Countries []Country `json:"countries"`

	// GoogleKm Google's own distance figure summed over the window's activities — the independent check routed distance is validated against in phase 3. 0 when the window holds no activities.
	GoogleKm     float64 `json:"google_km"`
	InferredKm   float64 `json:"inferred_km"`
	Legs         []Leg   `json:"legs"`
	MergedPoints int     `json:"merged_points"`
	ObservedKm   float64 `json:"observed_km"`

	// Params Exactly the parameters that produced this assembly (invariant 3).
	Params          map[string]interface{} `json:"params"`
	RawPointsKept   int                    `json:"raw_points_kept"`
	Stops           []Stop                 `json:"stops"`
	TotalKm         float64                `json:"total_km"`
	TracePointsKept int                    `json:"trace_points_kept"`
	WindowEnd       time.Time              `json:"window_end"`
	WindowStart     time.Time              `json:"window_start"`
}

// LatLng defines model for LatLng.
type LatLng struct {
	Lat float64 `json:"lat"`
	Lon float64 `json:"lon"`
}

// Leg defines model for Leg.
type Leg struct {
	// DistanceKm Chord sum for observed legs; endpoint chord for gaps.
	DistanceKm float64   `json:"distance_km"`
	End        time.Time `json:"end"`

	// GapKind Present only when kind is "gap". Always "unknown" in phase 2; phase 3 classifies road gaps (routed) and air gaps (great-circle arcs) and consumes this field.
	GapKind *LegGapKind `json:"gap_kind,omitempty"`
	Kind    LegKind     `json:"kind"`

	// Points An observed leg carries its full point run; a gap leg carries exactly its two endpoints.
	Points []TimedPoint `json:"points"`
	Start  time.Time    `json:"start"`
}

// LegGapKind Present only when kind is "gap". Always "unknown" in phase 2; phase 3 classifies road gaps (routed) and air gaps (great-circle arcs) and consumes this field.
type LegGapKind string

// LegKind defines model for Leg.Kind.
type LegKind string

// ModeCount defines model for ModeCount.
type ModeCount struct {
	// Mode Google's mode guess, e.g. IN_PASSENGER_VEHICLE. Unreliable at extremes.
	Mode string `json:"mode"`
	N    int    `json:"n"`
}

// NameSuggestion defines model for NameSuggestion.
type NameSuggestion struct {
	// Name Absent when there is nothing to suggest.
	Name *string `json:"name,omitempty"`

	// Source Which suggester answered — "none" for the null implementation.
	Source string `json:"source"`
}

// Run defines model for Run.
type Run struct {
	Id              int64 `json:"id"`
	OutliersDropped int   `json:"outliers_dropped"`

	// Params Exactly the parameters that produced this run (invariant 3).
	Params map[string]interface{} `json:"params"`
	RanAt  time.Time              `json:"ran_at"`
}

// ScoreComponent defines model for ScoreComponent.
type ScoreComponent struct {
	// Contribution Points contributed to the 0–100 score; contributions sum to it.
	Contribution float64 `json:"contribution"`

	// Name e.g. distance_from_home, destination_dwell.
	Name string `json:"name"`

	// Normalized Raw scaled against its saturation anchor, clamped to [0,1].
	Normalized float64 `json:"normalized"`

	// Present False when the component could not be computed; its weight was redistributed across the rest, never scored as zero.
	Present bool `json:"present"`

	// Raw Measured value in `unit`; 0 when not present.
	Raw  float64 `json:"raw"`
	Unit string  `json:"unit"`

	// Weight Configured weight, before any redistribution.
	Weight float64 `json:"weight"`
}

// Stop defines model for Stop.
type Stop struct {
	// DisplacementKm First-to-last straight line during the halt, not path sum.
	DisplacementKm float64   `json:"displacement_km"`
	End            time.Time `json:"end"`
	Loc            LatLng    `json:"loc"`
	Points         int       `json:"points"`
	Start          time.Time `json:"start"`
}

// TimedPoint defines model for TimedPoint.
type TimedPoint struct {
	Lat float64   `json:"lat"`
	Lon float64   `json:"lon"`
	T   time.Time `json:"t"`
}

// DecideCandidateJSONRequestBody defines body for DecideCandidate for application/json ContentType.
type DecideCandidateJSONRequestBody = DecisionRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListCandidates The latest detection run's candidates, with decision state attached
	// (GET /candidates)
	ListCandidates(w http.ResponseWriter, r *http.Request)
	// DecideCandidate Confirm or dismiss a candidate
	// (POST /candidates/{id}/decision)
	DecideCandidate(w http.ResponseWriter, r *http.Request, id int64)
	// GetCandidateJourney The journey reconstruction for a candidate of the latest run
	// (GET /candidates/{id}/journey)
	GetCandidateJourney(w http.ResponseWriter, r *http.Request, id int64)
	// SuggestCandidateName A proposed name for the candidate's adventure
	// (GET /candidates/{id}/name-suggestion)
	SuggestCandidateName(w http.ResponseWriter, r *http.Request, id int64)
	// GetHealth Liveness check
	// (GET /healthz)
	GetHealth(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListCandidates operation middleware
func (siw *ServerInterfaceWrapper) ListCandidates(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCandidates(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DecideCandidate operation middleware
func (siw *ServerInterfaceWrapper) DecideCandidate(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DecideCandidate(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCandidateJourney operation middleware
func (siw *ServerInterfaceWrapper) GetCandidateJourney(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCandidateJourney(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SuggestCandidateName operation middleware
func (siw *ServerInterfaceWrapper) SuggestCandidateName(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SuggestCandidateName(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/healthz", wrapper.GetHealth)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/candidates", wrapper.ListCandidates)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/candidates/{id}/journey", wrapper.GetCandidateJourney)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/candidates/{id}/name-suggestion", wrapper.SuggestCandidateName)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/candidates/{id}/decision", wrapper.DecideCandidate)

	return m
}

type ListCandidatesRequestObject struct {
}

type ListCandidatesResponseObject interface {
	VisitListCandidatesResponse(w http.ResponseWriter) error
}

type ListCandidates200JSONResponse CandidateList

func (response ListCandidates200JSONResponse) VisitListCandidatesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type DecideCandidateRequestObject struct {
	Id   int64 `json:"id"`
	Body *DecideCandidateJSONRequestBody
}

type DecideCandidateResponseObject interface {
	VisitDecideCandidateResponse(w http.ResponseWriter) error
}

type DecideCandidate200JSONResponse Decision

func (response DecideCandidate200JSONResponse) VisitDecideCandidateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type DecideCandidate400JSONResponse Error

func (response DecideCandidate400JSONResponse) VisitDecideCandidateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type DecideCandidate404JSONResponse Error

func (response DecideCandidate404JSONResponse) VisitDecideCandidateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetCandidateJourneyRequestObject struct {
	Id int64 `json:"id"`
}

type GetCandidateJourneyResponseObject interface {
	VisitGetCandidateJourneyResponse(w http.ResponseWriter) error
}

type GetCandidateJourney200JSONResponse Journey

func (response GetCandidateJourney200JSONResponse) VisitGetCandidateJourneyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetCandidateJourney404JSONResponse Error

func (response GetCandidateJourney404JSONResponse) VisitGetCandidateJourneyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type SuggestCandidateNameRequestObject struct {
	Id int64 `json:"id"`
}

type SuggestCandidateNameResponseObject interface {
	VisitSuggestCandidateNameResponse(w http.ResponseWriter) error
}

type SuggestCandidateName200JSONResponse NameSuggestion

func (response SuggestCandidateName200JSONResponse) VisitSuggestCandidateNameResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SuggestCandidateName404JSONResponse Error

func (response SuggestCandidateName404JSONResponse) VisitSuggestCandidateNameResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type SuggestCandidateName502JSONResponse Error

func (response SuggestCandidateName502JSONResponse) VisitSuggestCandidateNameResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(502)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse Health

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// ListCandidates The latest detection run's candidates, with decision state attached
	// (GET /candidates)
	ListCandidates(ctx context.Context, request ListCandidatesRequestObject) (ListCandidatesResponseObject, error)
	// DecideCandidate Confirm or dismiss a candidate
	// (POST /candidates/{id}/decision)
	DecideCandidate(ctx context.Context, request DecideCandidateRequestObject) (DecideCandidateResponseObject, error)
	// GetCandidateJourney The journey reconstruction for a candidate of the latest run
	// (GET /candidates/{id}/journey)
	GetCandidateJourney(ctx context.Context, request GetCandidateJourneyRequestObject) (GetCandidateJourneyResponseObject, error)
	// SuggestCandidateName A proposed name for the candidate's adventure
	// (GET /candidates/{id}/name-suggestion)
	SuggestCandidateName(ctx context.Context, request SuggestCandidateNameRequestObject) (SuggestCandidateNameResponseObject, error)
	// GetHealth Liveness check
	// (GET /healthz)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListCandidates operation middleware
func (sh *strictHandler) ListCandidates(w http.ResponseWriter, r *http.Request) {
	var request ListCandidatesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListCandidates(ctx, request.(ListCandidatesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListCandidates")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListCandidatesResponseObject); ok {
		if err := validResponse.VisitListCandidatesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DecideCandidate operation middleware
func (sh *strictHandler) DecideCandidate(w http.ResponseWriter, r *http.Request, id int64) {
	var request DecideCandidateRequestObject

	request.Id = id

	var body DecideCandidateJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DecideCandidate(ctx, request.(DecideCandidateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DecideCandidate")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DecideCandidateResponseObject); ok {
		if err := validResponse.VisitDecideCandidateResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetCandidateJourney operation middleware
func (sh *strictHandler) GetCandidateJourney(w http.ResponseWriter, r *http.Request, id int64) {
	var request GetCandidateJourneyRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetCandidateJourney(ctx, request.(GetCandidateJourneyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCandidateJourney")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetCandidateJourneyResponseObject); ok {
		if err := validResponse.VisitGetCandidateJourneyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SuggestCandidateName operation middleware
func (sh *strictHandler) SuggestCandidateName(w http.ResponseWriter, r *http.Request, id int64) {
	var request SuggestCandidateNameRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SuggestCandidateName(ctx, request.(SuggestCandidateNameRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SuggestCandidateName")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SuggestCandidateNameResponseObject); ok {
		if err := validResponse.VisitSuggestCandidateNameResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
