/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The latest detection run's candidates, with decision state attached
         * @description Candidates come from the most recent detection run. Each carries its matched decision, if any; decisions no current candidate matched are returned separately as orphans, because a decision is never silently lost (BRIEF §3.1). When no detection run exists yet, `run` is omitted, `candidates` is empty, and every decision is an orphan.
         */
        get: operations["listCandidates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/candidates/{id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm or dismiss a candidate
         * @description Records a decision on a candidate of the latest run, snapshotting the candidate's span and destination as the decision's anchor. If the candidate already has a matched decision, that decision is updated in place and its anchor refreshed; otherwise a new decision is created.
         */
        post: operations["decideCandidate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @example ok */
            status: string;
        };
        LatLng: {
            /** Format: double */
            lat: number;
            /** Format: double */
            lon: number;
        };
        ModeCount: {
            /** @description Google's mode guess, e.g. IN_PASSENGER_VEHICLE. Unreliable at extremes. */
            mode: string;
            n: number;
        };
        Run: {
            /** Format: int64 */
            id: number;
            /** Format: date-time */
            ran_at: string;
            /** @description Exactly the parameters that produced this run (invariant 3). */
            params: {
                [key: string]: unknown;
            };
            outliers_dropped: number;
        };
        Candidate: {
            /** Format: int64 */
            id: number;
            /** Format: date-time */
            span_start: string;
            /** Format: date-time */
            span_end: string;
            /** Format: double */
            days: number;
            dest: components["schemas"]["LatLng"];
            /** @description Distance home → farthest place dwelt, never merely passed through. */
            dest_km: number;
            track_km: number;
            stops: number;
            repeat: number;
            obs_count: number;
            /** @description The span begins at the window edge; the real journey started earlier (bug 4). */
            start_truncated: boolean;
            end_truncated: boolean;
            modes: components["schemas"]["ModeCount"][];
            decision?: components["schemas"]["Decision"];
        };
        Decision: {
            /** Format: int64 */
            id: number;
            /** @enum {string} */
            action: "confirmed" | "dismissed";
            /** @description Present when action is confirmed. */
            name?: string;
            /** Format: date-time */
            updated_at: string;
        };
        CandidateList: {
            run?: components["schemas"]["Run"];
            candidates: components["schemas"]["Candidate"][];
            /** @description Decisions no current candidate matched. Never hidden: a parameter change may orphan a decision, and lowering it back re-matches. */
            orphaned_decisions: components["schemas"]["Decision"][];
        };
        DecisionRequest: {
            /** @enum {string} */
            action: "confirmed" | "dismissed";
            /** @description Required when action is confirmed. */
            name?: string;
        };
        Error: {
            error: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    listCandidates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Candidates and orphaned decisions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateList"];
                };
            };
        };
    };
    decideCandidate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Candidate id from the latest run. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionRequest"];
            };
        };
        responses: {
            /** @description The decision as stored. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Decision"];
                };
            };
            /** @description Invalid request — confirming without a name, or an unknown action. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No such candidate in the latest run (stale id after re-detection). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
