/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The latest detection run's candidates, with decision state attached
         * @description Candidates come from the most recent detection run. Each carries its matched decision, if any; decisions no current candidate matched are returned separately as orphans, because a decision is never silently lost (BRIEF §3.1). When no detection run exists yet, `run` is omitted, `candidates` is empty, and every decision is an orphan.
         */
        get: operations["listCandidates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/candidates/{id}/journey": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The journey reconstruction for a candidate of the latest run
         * @description Assembles the candidate's span into an ordered list of legs, each observed or a gap — never one undifferentiated line (CLAUDE.md invariant 5); every leg carries its kind so confidence survives to the renderer (invariant 8). Straight lines only in phase 2: gap_kind is always "unknown" until phase 3 classifies road and air gaps. The journey is derived on demand from immutable observations, and the response echoes the parameters that produced it (invariant 3).
         */
        get: operations["getCandidateJourney"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/candidates/{id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm or dismiss a candidate
         * @description Records a decision on a candidate of the latest run, snapshotting the candidate's span and destination as the decision's anchor. If the candidate already has a matched decision, that decision is updated in place and its anchor refreshed; otherwise a new decision is created.
         */
        post: operations["decideCandidate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @example ok */
            status: string;
        };
        LatLng: {
            /** Format: double */
            lat: number;
            /** Format: double */
            lon: number;
        };
        ModeCount: {
            /** @description Google's mode guess, e.g. IN_PASSENGER_VEHICLE. Unreliable at extremes. */
            mode: string;
            n: number;
        };
        Run: {
            /** Format: int64 */
            id: number;
            /** Format: date-time */
            ran_at: string;
            /** @description Exactly the parameters that produced this run (invariant 3). */
            params: {
                [key: string]: unknown;
            };
            outliers_dropped: number;
        };
        Candidate: {
            /** Format: int64 */
            id: number;
            /** Format: date-time */
            span_start: string;
            /** Format: date-time */
            span_end: string;
            /** Format: double */
            days: number;
            dest: components["schemas"]["LatLng"];
            /** @description Distance home → farthest place dwelt, never merely passed through. */
            dest_km: number;
            track_km: number;
            stops: number;
            repeat: number;
            obs_count: number;
            /** @description The span begins at the window edge; the real journey started earlier (bug 4). */
            start_truncated: boolean;
            end_truncated: boolean;
            modes: components["schemas"]["ModeCount"][];
            decision?: components["schemas"]["Decision"];
        };
        Decision: {
            /** Format: int64 */
            id: number;
            /** @enum {string} */
            action: "confirmed" | "dismissed";
            /** @description Present when action is confirmed. */
            name?: string;
            /** Format: date-time */
            updated_at: string;
        };
        CandidateList: {
            run?: components["schemas"]["Run"];
            candidates: components["schemas"]["Candidate"][];
            /** @description Decisions no current candidate matched. Never hidden: a parameter change may orphan a decision, and lowering it back re-matches. */
            orphaned_decisions: components["schemas"]["Decision"][];
        };
        DecisionRequest: {
            /** @enum {string} */
            action: "confirmed" | "dismissed";
            /** @description Required when action is confirmed. */
            name?: string;
        };
        TimedPoint: {
            /** Format: date-time */
            t: string;
            /** Format: double */
            lat: number;
            /** Format: double */
            lon: number;
        };
        Leg: {
            /** @enum {string} */
            kind: "observed" | "gap";
            /**
             * @description Present only when kind is "gap". Always "unknown" in phase 2; phase 3 classifies road gaps (routed) and air gaps (great-circle arcs) and consumes this field.
             * @enum {string}
             */
            gap_kind?: "unknown" | "road" | "air";
            /** @description An observed leg carries its full point run; a gap leg carries exactly its two endpoints. */
            points: components["schemas"]["TimedPoint"][];
            /**
             * Format: double
             * @description Chord sum for observed legs; endpoint chord for gaps.
             */
            distance_km: number;
            /** Format: date-time */
            start: string;
            /** Format: date-time */
            end: string;
        };
        Stop: {
            /** Format: date-time */
            start: string;
            /** Format: date-time */
            end: string;
            loc: components["schemas"]["LatLng"];
            points: number;
            /**
             * Format: double
             * @description First-to-last straight line during the halt, not path sum.
             */
            displacement_km: number;
        };
        Country: {
            /** @description ISO 3166-1 alpha-2 where Natural Earth provides one (Kosovo's XK is user-assigned); territories without any alpha-2 carry Natural Earth's three-letter ADM0_A3 instead. */
            iso_code: string;
            name: string;
        };
        Journey: {
            /** Format: date-time */
            window_start: string;
            /** Format: date-time */
            window_end: string;
            /** @description Exactly the parameters that produced this assembly (invariant 3). */
            params: {
                [key: string]: unknown;
            };
            legs: components["schemas"]["Leg"][];
            stops: components["schemas"]["Stop"][];
            /** @description Countries the route's points fall in, ordered by first appearance along the journey. Derived locally by point-in-polygon against bundled Natural Earth polygons — never a network lookup. Empty when `roadbook countries` has not been run. Border-adjacent points can misattribute at 1:110m resolution; the UI labels this line as derived. */
            countries: components["schemas"]["Country"][];
            /** Format: double */
            total_km: number;
            /** Format: double */
            observed_km: number;
            /** Format: double */
            inferred_km: number;
            /**
             * Format: double
             * @description Google's own distance figure summed over the window's activities — the independent check routed distance is validated against in phase 3. 0 when the window holds no activities.
             */
            google_km: number;
            merged_points: number;
            trace_points_kept: number;
            raw_points_kept: number;
        };
        Error: {
            error: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    listCandidates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Candidates and orphaned decisions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateList"];
                };
            };
        };
    };
    getCandidateJourney: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Candidate id from the latest run. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The assembled journey. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Journey"];
                };
            };
            /** @description No such candidate in the latest run (stale id after re-detection). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    decideCandidate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Candidate id from the latest run. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionRequest"];
            };
        };
        responses: {
            /** @description The decision as stored. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Decision"];
                };
            };
            /** @description Invalid request — confirming without a name, or an unknown action. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No such candidate in the latest run (stale id after re-detection). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
