/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness check
         * @description Answers 200 only when a database round-trip succeeds — a listening socket with a dead database behind it is exactly the not-ready state the check exists to catch (phase 5 BRIEF §3A). The compose healthcheck gates dependent services on this.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Every import attempt, newest first
         * @description Import bookkeeping (phase 5 BRIEF §3B): each attempt is recorded before parsing and finalised as completed or failed, so a failure is visible in the product. detected_format is the sniffer's stable format label — evidence that stays queryable while user-facing error prose gets reworded.
         */
        get: operations["listImports"];
        put?: never;
        /**
         * Upload a Timeline export and import it
         * @description The browser import path (phase 7 BRIEF §§1.1–1.3, §3A). The file streams to the instance's uploads directory — named by its SHA-256, retained after import (the export may be irreplaceable: rawSignals windows expire at the source) — and the head is sniffed before the request returns, so a wrong file is rejected synchronously with its stable format label. 202 means accepted: the imports row exists with status "running" and the parse continues in the background; poll GET /imports/{id}. On success detection runs automatically with default parameters (recorded per run as ever), reported via detect_status on the same resource. One import runs at a time; a concurrent attempt gets 409. Re-uploading identical bytes stores no second file and re-imports idempotently (an all-skipped row).
         */
        post: operations["uploadImport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/imports/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload a batch of photos as an import source
         * @description The photo-ingestion path (phase 11 BRIEF §4C). Repeatable `file` parts — photos (JPEG or HEIC) and their Takeout JSON sidecars — stream through metadata extraction one at a time: each usable photo becomes one position fix in the observation stratum plus a photo record (and a thumbnail where the format is decodable); the original bytes are discarded, never retained (§4D — the records are the durable product, and this is the privacy-shaped answer). Unlike the Timeline path there is no all-or-nothing rule: a camera roll is many files, so the response carries a per-file verdict and the import row records what the batch contributed. The import itself completes before the response; detection then runs in the background with default parameters, reported via detect_status on GET /imports/{id}. One import runs at a time; a concurrent attempt gets 409. Re-uploading the same photos is idempotent — no new fixes, no new records, no second thumbnail.
         */
        post: operations["uploadPhotoImport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/imports/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One import attempt, by id
         * @description The polling endpoint for an upload in progress (phase 7 BRIEF §1.2): status running → completed/failed, then detect_status for the automatic detection that follows a successful upload import.
         */
        get: operations["getImport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The latest detection run's candidates, with decision state attached
         * @description Candidates come from the most recent detection run. Each carries its matched decision, if any; decisions no current candidate matched are returned separately as orphans, because a decision is never silently lost (BRIEF §3.1). When no detection run exists yet, `run` is omitted, `candidates` is empty, and every decision is an orphan.
         */
        get: operations["listCandidates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/candidates/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Decide several candidates in one atomic request
         * @description Bulk triage (phase 11 §6.1, the first pilot report's friction): confirm or dismiss many candidates at once. All-or-nothing — every item is validated (a confirm carries a non-empty name; every id is in the latest run) and applied in one transaction, or nothing is recorded and the error says why. Anchoring and re-decide semantics are exactly the single-decision endpoint's, per item.
         */
        post: operations["decideCandidatesBulk"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/candidates/{id}/journey": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The journey reconstruction for a candidate of the latest run
         * @description Assembles the candidate's span into an ordered list of legs, each observed or a gap — never one undifferentiated line (CLAUDE.md invariant 5); every leg carries its kind so confidence survives to the renderer (invariant 8). Straight lines only in phase 2: gap_kind is always "unknown" until phase 3 classifies road and air gaps. The journey is derived on demand from immutable observations, and the response echoes the parameters that produced it (invariant 3).
         */
        get: operations["getCandidateJourney"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/candidates/{id}/name-suggestion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A proposed name for the candidate's adventure
         * @description One-shot lookup on the destination coordinate through the configured Suggester (BRIEF §1.7) — the null implementation by default, a reverse geocoder when enabled at serve time. The suggestion is prefill for the confirm step's name input and is never applied automatically. An absent name is a real answer: nothing to suggest.
         */
        get: operations["suggestCandidateName"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/candidates/{id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm or dismiss a candidate
         * @description Records a decision on a candidate of the latest run, snapshotting the candidate's span and destination as the decision's anchor. If the candidate already has a matched decision, that decision is updated in place and its anchor refreshed; otherwise a new decision is created.
         */
        post: operations["decideCandidate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/candidates/{id}/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The photos of a candidate's confirmed adventure
         * @description Photos attached to the decision matched to this candidate. An empty list for a confirmed adventure with no uploads; 409 when the candidate has no confirmed decision.
         */
        get: operations["listCandidatePhotos"];
        put?: never;
        /**
         * Upload photos (and Takeout sidecars) to a confirmed adventure
         * @description Multipart upload through the one API boundary (BRIEF §1.3): images and optional Google Photos Takeout JSON sidecars in a single request. Only the thumbnail and extracted metadata are stored; original bytes are discarded after extraction and never written to disk. Results are per-file — one unsupported file never fails the batch. Re-upload of identical bytes reports "duplicate" and stores nothing (content- hash idempotency, the imports precedent). Sidecars pair with their image by filename, falling back to their title field.
         */
        post: operations["uploadCandidatePhotos"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/candidates/{id}/import-photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Photo-import records whose capture falls in this candidate's span
         * @description The photo records (phase 11 §4D) whose capture instant lies inside the candidate's span, joined at read time and never stored against the candidate (DECISIONS 2026-08-26): records ride imports, so re-detection cannot orphan them and there is nothing to migrate. Available for any candidate of the latest run — records are facts about the window, and seeing them helps triage as much as it decorates a confirmed adventure. Placement fields are derived against the same assembled journey the page draws, exactly as for attached photos.
         */
        get: operations["listCandidateImportPhotos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/import-photos/{id}/thumbnail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The stored thumbnail of a photo-import record
         * @description JPEG bytes from the shared thumbnail store, metadata-stripped like every thumbnail. 404 both for an unknown record and for a record with no thumbnail (HEIC: metadata readable at ingest, pixels not decodable — thumb_w/thumb_h are 0 on the record).
         */
        get: operations["getImportPhotoThumbnail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/photos/{id}/thumbnail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The stored thumbnail image
         * @description JPEG bytes, re-encoded pixels only — the thumbnailer strips all embedded metadata, so this file carries no position or timestamp (BRIEF §1.2). The browser reaches this through the Next.js proxy route handler, never directly.
         */
        get: operations["getPhotoThumbnail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/photos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete one photo
         * @description Removes the row, then the thumbnail file — in that order, so a mid-failure leaves unreachable garbage rather than a broken image (BRIEF §3B). User-initiated only; nothing automated deletes photos.
         */
        delete: operations["deletePhoto"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @example ok */
            status: string;
        };
        Import: {
            /** Format: int64 */
            id: number;
            /** @description Provenance label, defaulting to the source file name. */
            source_label: string;
            /**
             * Format: date-time
             * @description Optional import date window (the -from flag). Absent means unbounded.
             */
            window_start?: string;
            /** Format: date-time */
            window_end?: string;
            /** Format: date-time */
            imported_at: string;
            visits: number;
            activities: number;
            points: number;
            raw_positions: number;
            skipped: number;
            /** @enum {string} */
            status: "running" | "completed" | "failed";
            /** @description The user-facing failure message — prose, subject to rewording; never the queryable evidence. */
            error?: string;
            /** @description The sniffer's stable format label (phone-timeline, records-json, semantic-history, …). Absent when the input was never recognised. */
            detected_format?: string;
            /** @description How many observations were genuinely new — the per-type counters record what the file contained; this records what the database gained. Zero on a duplicate upload ("nothing new"). Absent on rows from before this field existed. */
            inserted?: number;
            /** @description SHA-256 of the uploaded file, upload-path imports only — the retained file's name in the uploads directory (the photos content-hash precedent). Absent on CLI imports. */
            content_hash?: string;
            /**
             * @description Status of the automatic detection that follows a successful upload import (phase 7 BRIEF §3D). Absent when no auto-detect was triggered (CLI imports, failed imports). A detection failure never marks the import failed — the import row describes the import.
             * @enum {string}
             */
            detect_status?: "running" | "completed" | "failed";
        };
        ImportRejection: {
            /** @description The sniffer's actionable message — prose, rewordable. */
            error: string;
            /** @description The stable format label (zip, records-json, …) — what the file actually is, for mapping to a walkthrough anchor. Absent when the input was not recognisable at all. */
            detected_format?: string;
        };
        ImportList: {
            imports: components["schemas"]["Import"][];
        };
        PhotoImportResult: {
            import: components["schemas"]["Import"];
            files: components["schemas"]["PhotoImportFile"][];
        };
        PhotoImportFile: {
            file: string;
            /**
             * @description What this file contributed. "fix" — a position fix was extracted (with a photo record, and a thumbnail where decodable); "no_position"/"no_time" — a recognised photo carrying no usable reading (photos are stored only when they place something); sidecar verdicts mirror the phase-4 upload; "unsupported" carries the sniffer's actionable message.
             * @enum {string}
             */
            status: "fix" | "no_position" | "no_time" | "sidecar_paired" | "sidecar_unpaired" | "unsupported";
            /** @description Prose for rejected files — rewordable, never the label. */
            message?: string;
        };
        LatLng: {
            /** Format: double */
            lat: number;
            /** Format: double */
            lon: number;
        };
        ModeCount: {
            /** @description Google's mode guess, e.g. IN_PASSENGER_VEHICLE. Unreliable at extremes. */
            mode: string;
            n: number;
        };
        Run: {
            /** Format: int64 */
            id: number;
            /** Format: date-time */
            ran_at: string;
            /** @description Exactly the parameters that produced this run (invariant 3). */
            params: {
                [key: string]: unknown;
            };
            outliers_dropped: number;
        };
        Candidate: {
            /** Format: int64 */
            id: number;
            /** Format: date-time */
            span_start: string;
            /** Format: date-time */
            span_end: string;
            /** Format: double */
            days: number;
            dest: components["schemas"]["LatLng"];
            /** @description Distance home → farthest place dwelt, never merely passed through. */
            dest_km: number;
            track_km: number;
            stops: number;
            repeat: number;
            obs_count: number;
            /** @description The span begins at the window edge; the real journey started earlier (bug 4). */
            start_truncated: boolean;
            end_truncated: boolean;
            modes: components["schemas"]["ModeCount"][];
            /**
             * Format: double
             * @description Confidence 0–100 from named weighted components (weights recorded in the run's params). Ranking and decision support only — never a filter, never auto-confirmation. Absent on candidates stored before scoring existed: not scored is different information than a low score.
             */
            score?: number;
            /** @description The per-component arithmetic that reproduces `score`. */
            score_breakdown?: components["schemas"]["ScoreComponent"][];
            decision?: components["schemas"]["Decision"];
        };
        ScoreComponent: {
            /** @description e.g. distance_from_home, destination_dwell. */
            name: string;
            /** @description False when the component could not be computed; its weight was redistributed across the rest, never scored as zero. */
            present: boolean;
            /**
             * Format: double
             * @description Configured weight, before any redistribution.
             */
            weight: number;
            /**
             * Format: double
             * @description Measured value in `unit`; 0 when not present.
             */
            raw: number;
            unit: string;
            /**
             * Format: double
             * @description Raw scaled against its saturation anchor, clamped to [0,1].
             */
            normalized: number;
            /**
             * Format: double
             * @description Points contributed to the 0–100 score; contributions sum to it.
             */
            contribution: number;
        };
        NameSuggestion: {
            /** @description Absent when there is nothing to suggest. */
            name?: string;
            /** @description Which suggester answered — "none" for the null implementation. */
            source: string;
        };
        Decision: {
            /** Format: int64 */
            id: number;
            /** @enum {string} */
            action: "confirmed" | "dismissed";
            /** @description Present when action is confirmed. */
            name?: string;
            /** Format: date-time */
            updated_at: string;
        };
        CandidateList: {
            run?: components["schemas"]["Run"];
            candidates: components["schemas"]["Candidate"][];
            /** @description Decisions no current candidate matched. Never hidden: a parameter change may orphan a decision, and lowering it back re-matches. */
            orphaned_decisions: components["schemas"]["Decision"][];
        };
        DecisionRequest: {
            /** @enum {string} */
            action: "confirmed" | "dismissed";
            /** @description Required when action is confirmed. */
            name?: string;
        };
        TimedPoint: {
            /** Format: date-time */
            t: string;
            /** Format: double */
            lat: number;
            /** Format: double */
            lon: number;
        };
        Leg: {
            /** @enum {string} */
            kind: "observed" | "gap";
            /**
             * @description Present only when kind is "gap". "air": the gap's implied speed (endpoint chord over duration) met the air_speed_min_kmh parameter — rendered as a great-circle arc, never routed, excluded from road-distance validation. "road": the routing cache supplied road geometry for this gap. "unknown": neither — drawn as a dashed straight line that is not a route.
             * @enum {string}
             */
            gap_kind?: "unknown" | "road" | "air";
            /** @description An observed leg carries its full point run; a gap leg carries exactly its two endpoints. */
            points: components["schemas"]["TimedPoint"][];
            /**
             * Format: double
             * @description Chord sum for observed legs; endpoint chord for gaps.
             */
            distance_km: number;
            /** @description Road geometry from the routing cache — present only when gap_kind is "road". Rides alongside points (which still holds exactly the two timestamped endpoints): routed vertices have no timestamps, and are inference, not measurement. */
            routed_points?: components["schemas"]["LatLng"][];
            /**
             * Format: double
             * @description The routed road distance — present only when gap_kind is "road". distance_km keeps its chord meaning regardless.
             */
            routed_km?: number;
            /** Format: date-time */
            start: string;
            /** Format: date-time */
            end: string;
        };
        Stop: {
            /** Format: date-time */
            start: string;
            /** Format: date-time */
            end: string;
            loc: components["schemas"]["LatLng"];
            points: number;
            /**
             * Format: double
             * @description First-to-last straight line during the halt, not path sum.
             */
            displacement_km: number;
        };
        Country: {
            /** @description ISO 3166-1 alpha-2 where Natural Earth provides one (Kosovo's XK is user-assigned); territories without any alpha-2 carry Natural Earth's three-letter ADM0_A3 instead. */
            iso_code: string;
            name: string;
        };
        Journey: {
            /** Format: date-time */
            window_start: string;
            /** Format: date-time */
            window_end: string;
            /** @description Exactly the parameters that produced this assembly (invariant 3). */
            params: {
                [key: string]: unknown;
            };
            legs: components["schemas"]["Leg"][];
            stops: components["schemas"]["Stop"][];
            /** @description Countries the route's points fall in, ordered by first appearance along the journey. Derived locally by point-in-polygon against bundled Natural Earth polygons — never a network lookup. Empty when `roadbook countries` has not been run. Border-adjacent points can misattribute at 1:110m resolution; the UI labels this line as derived. */
            countries: components["schemas"]["Country"][];
            /** Format: double */
            total_km: number;
            /** Format: double */
            observed_km: number;
            /** Format: double */
            inferred_km: number;
            /**
             * Format: double
             * @description Chord sum over air-classified gaps — a subset of inferred_km. The endpoint chord is the great-circle distance, so it is also the arc's length. Excluded from road-distance validation. 0 for a ground journey.
             */
            air_km: number;
            /**
             * Format: double
             * @description Chord sum over gaps still unknown after the routing cache was consulted — the visibly-unfilled remainder. A router that cannot fill a gap leaves it here by design (patchy OSM coverage is the expected case, not an error).
             */
            unknown_km: number;
            /**
             * Format: double
             * @description Routed road distance summed over road legs. 0 when nothing is routed — the product is fully usable without a router.
             */
            routed_km: number;
            /**
             * Format: double
             * @description The road-comparable reconstruction: observed + routed + unknown chords. Air legs are excluded by construction.
             */
            ground_km: number;
            /**
             * Format: double
             * @description Google's own activity distances minus FLYING-mode activities — the comparable side of the road validation. Air must leave both sides or neither. Mode is a guess: a flight Google mislabelled as ground inflates this figure, and the divergence flag is the tripwire that surfaces it.
             */
            google_ground_km: number;
            /** @description Source-asserted per-mode distance (phase 11 §6.2): the window's activity distances summed by Google's own mode labels, ordered km-descending. These are the source's guesses (recorded failures: a 1,023 km "motorcycling" relocation, probability-0.00 modes; the pipeline itself trusts speed over mode for flight), so display keeps them visually subordinate, labels the source, and never sums them against measured geometry. Absent — not empty — when the journey's evidence carries no activities at all (photo-sourced journeys): the display states that rather than showing zeros. */
            mode_breakdown?: components["schemas"]["ModeKm"][];
            /**
             * Format: double
             * @description Signed percentage by which ground_km differs from google_ground_km. Absent when Google recorded no ground distance in the window — nothing to compare is not zero divergence. A conversation starter, never a gate: unroutable gaps under-count, OSM detours over-count, and both explain themselves on the map.
             */
            divergence_pct?: number;
            /** @description True when divergence_pct exceeds the divergence_warn_pct parameter (echoed in params) in either direction. Absent whenever divergence_pct is absent. Computed server-side so the frontend renders the flag without owning the threshold. */
            divergence_flagged?: boolean;
            /**
             * Format: double
             * @description Google's own distance figure summed over the window's activities — the independent check routed distance is validated against in phase 3. 0 when the window holds no activities.
             */
            google_km: number;
            merged_points: number;
            trace_points_kept: number;
            raw_points_kept: number;
        };
        Photo: {
            /** Format: int64 */
            id: number;
            original_name: string;
            /**
             * Format: date-time
             * @description The resolved capture instant. Absent when no rung of the time ladder resolved (time_source "none") — the photo is stored and shown, but unplaced on map and timeline.
             */
            taken_at?: string;
            /** @description Civil offset for display, seconds east of UTC. Present exactly when taken_at is. */
            taken_offset_sec?: number;
            /**
             * @description Which rung of the resolution ladder produced taken_at (BRIEF §3E), strongest first — the GPS receiver's own UTC clock, the explicit EXIF offset tag, the Takeout sidecar's epoch, or the wall clock interpreted in the adventure's own offset (stated as the weakest rung; wrong by the zone difference on multi-zone adventures).
             * @enum {string}
             */
            time_source: "gps" | "exif_offset" | "sidecar" | "exif_local" | "none";
            pos?: components["schemas"]["LatLng"];
            /**
             * @description Which reading produced pos (BRIEF §3D) — the camera's own GPS block, or Google's copy from the Takeout sidecar. "none": no position; the photo appears in the strip but not on the map.
             * @enum {string}
             */
            pos_source: "exif" | "sidecar" | "none";
            /** @description Thumbnail pixel width, post-orientation. */
            thumb_w: number;
            thumb_h: number;
            /** Format: date-time */
            uploaded_at: string;
            /**
             * @description Which element of the journey held this photo's instant — and therefore which drawn geometry distance_from_route_m was measured against (BRIEF §3G) - an observed leg's measured points, a road gap's routed polyline, an unknown gap's chord, or a stop's location. Absent when the photo is unplaced: no position, no resolved instant, or an instant outside every leg and stop. Derived at read time, never stored — re-detection re-places photos automatically.
             * @enum {string}
             */
            place_kind?: "observed" | "road" | "unknown" | "air" | "stop";
            /** @description Index into the journey's legs. Present for leg place kinds. */
            leg_index?: number;
            /** @description Index into the journey's stops. Present when place_kind is "stop". */
            stop_index?: number;
            /**
             * Format: double
             * @description Point-to-polyline distance from the photo's position to the placed element's drawn geometry. Absent for place_kind "air": the arc is presentation between two endpoints, not a claimed path, so "far from it" asserts nothing.
             */
            distance_from_route_m?: number;
            /** @description True when distance_from_route_m exceeds the photo_far_warn_m parameter (echoed in the list's params). The photo's position is a measurement — the most accurate in the project — so the flag marks a disagreement between the photo and the inferred route, not a doubt about the photo. A conversation starter, never a gate. */
            far_flagged?: boolean;
        };
        BulkDecisionItem: {
            /**
             * Format: int64
             * @description Candidate id from the latest run.
             */
            id: number;
            /** @enum {string} */
            action: "confirmed" | "dismissed";
            /** @description Required, non-empty, when action is "confirmed". */
            name?: string;
        };
        BulkDecisionRequest: {
            decisions: components["schemas"]["BulkDecisionItem"][];
        };
        BulkDecisionResult: {
            /** @description How many decisions were applied (equals the request's count). */
            decided: number;
        };
        ModeKm: {
            /** @description The source's own label (IN_BUS, FLYING, …), unreworded. */
            mode: string;
            /** Format: double */
            km: number;
        };
        /** @description One photo-import record (phase 11 §4D), distinct from Photo deliberately: records ride imports and are never deletable from an adventure, while attached photos ride decisions and are — one schema for both would blur what each id can do. Records exist only for usable photos, so position and instant are always present. */
        ImportPhoto: {
            /** Format: int64 */
            id: number;
            /**
             * Format: int64
             * @description The photo import this record arrived in.
             */
            import_id: number;
            original_name: string;
            /** Format: date-time */
            taken_at: string;
            /** @description Civil offset for display, seconds east of UTC. */
            taken_offset_sec: number;
            /** @enum {string} */
            time_source: "gps" | "exif_offset" | "sidecar" | "exif_local";
            pos: components["schemas"]["LatLng"];
            /** @enum {string} */
            pos_source: "exif" | "sidecar";
            /** @description Thumbnail pixel width; 0 means no thumbnail (HEIC). */
            thumb_w: number;
            thumb_h: number;
            /** Format: date-time */
            uploaded_at: string;
            /**
             * @description Same read-time placement as Photo.place_kind, against the same drawn geometry. Absent when the instant falls outside every leg and stop of the assembled journey.
             * @enum {string}
             */
            place_kind?: "observed" | "road" | "unknown" | "air" | "stop";
            leg_index?: number;
            stop_index?: number;
            /** Format: double */
            distance_from_route_m?: number;
            far_flagged?: boolean;
        };
        ImportPhotoList: {
            photos: components["schemas"]["ImportPhoto"][];
            /** @description The placement parameters that produced the derived fields (invariant 3) — photo_far_warn_m today. */
            params: {
                [key: string]: unknown;
            };
        };
        PhotoUploadResult: {
            /** @description The uploaded filename this result is about. */
            file: string;
            /**
             * @description accepted — stored, thumbnail written. duplicate — identical bytes already stored (the existing photo is returned). rejected — not a supported photo; reason says what it actually is and what to do. sidecar_paired — a Takeout JSON consumed as metadata for paired_with. sidecar_unpaired — a sidecar naming no image in this upload; nothing stored.
             * @enum {string}
             */
            status: "accepted" | "duplicate" | "rejected" | "sidecar_paired" | "sidecar_unpaired";
            /** @description The actionable rejection message. Present when rejected. */
            reason?: string;
            /** @description The image filename a sidecar was applied to. */
            paired_with?: string;
            photo?: components["schemas"]["Photo"];
        };
        PhotoUploadResults: {
            results: components["schemas"]["PhotoUploadResult"][];
        };
        PhotoList: {
            photos: components["schemas"]["Photo"][];
            /** @description The placement parameters that produced the derived fields (invariant 3) — photo_far_warn_m today. */
            params: {
                [key: string]: unknown;
            };
        };
        Error: {
            error: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is up and the database answers. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description The database is unreachable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listImports: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All import attempts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportList"];
                };
            };
        };
    };
    uploadImport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description The Timeline export.
                     */
                    file: string;
                    /** @description Provenance label; defaults to the uploaded file's name (the source_label convention). */
                    label?: string;
                };
            };
        };
        responses: {
            /** @description Accepted — the upload is on disk and the import is running. The returned id is the polling handle. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Import"];
                };
            };
            /** @description The sniffer recognised a wrong input. detected_format carries the stable label so the front door can redirect to the right walkthrough instead of dead-ending; the rejected file is not retained. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportRejection"];
                };
            };
            /** @description An import is already running on this instance. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The upload exceeds the configured size limit. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    uploadPhotoImport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** @description Photos and sidecars; repeatable. */
                    file: string[];
                    /** @description Provenance label; defaults to "photo upload". */
                    label?: string;
                };
            };
        };
        responses: {
            /** @description The batch is imported (the import row is already completed) and automatic detection is running; the import id is the polling handle for detect_status. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoImportResult"];
                };
            };
            /** @description The request carried no file parts. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An import is already running on this instance. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getImport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The import attempt. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Import"];
                };
            };
            /** @description No such import. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listCandidates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Candidates and orphaned decisions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateList"];
                };
            };
        };
    };
    decideCandidatesBulk: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkDecisionRequest"];
            };
        };
        responses: {
            /** @description Every decision applied. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkDecisionResult"];
                };
            };
            /** @description Invalid request — empty list, an unknown action, a confirm without a name, or the same candidate twice. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description One or more ids are not in the latest run (stale after re-detection). Nothing was applied; the message names them. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getCandidateJourney: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Candidate id from the latest run. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The assembled journey. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Journey"];
                };
            };
            /** @description No such candidate in the latest run (stale id after re-detection). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    suggestCandidateName: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Candidate id from the latest run. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The suggestion, possibly empty. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NameSuggestion"];
                };
            };
            /** @description No such candidate in the latest run (stale id after re-detection). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The configured suggester could not be reached. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    decideCandidate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Candidate id from the latest run. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionRequest"];
            };
        };
        responses: {
            /** @description The decision as stored. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Decision"];
                };
            };
            /** @description Invalid request — confirming without a name, or an unknown action. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No such candidate in the latest run (stale id after re-detection). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listCandidatePhotos: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Candidate id from the latest run. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The photos, in upload order. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoList"];
                };
            };
            /** @description No such candidate in the latest run (stale id after re-detection). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The candidate has no confirmed decision. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    uploadCandidatePhotos: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Candidate id from the latest run. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    files?: string[];
                };
            };
        };
        responses: {
            /** @description One result per uploaded file, in upload order. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoUploadResults"];
                };
            };
            /** @description No such candidate in the latest run (stale id after re-detection). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The candidate has no confirmed decision. Photos attach to adventures — confirmed candidates — because they are user data and must not attach to disposable rows (BRIEF §3A). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listCandidateImportPhotos: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Candidate id from the latest run. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The records, in capture order. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportPhotoList"];
                };
            };
            /** @description No such candidate in the latest run (stale id after re-detection). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getImportPhotoThumbnail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The thumbnail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": string;
                };
            };
            /** @description No such record, or the record has no thumbnail. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getPhotoThumbnail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The thumbnail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": string;
                };
            };
            /** @description No such photo. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deletePhoto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such photo. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
